# Generated by Django 6.0.7 on 2026-09-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
                ('user_status', models.BooleanField(default=True)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_hours_per_day', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workentry',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='Latin1_General_CI_AI', db_column='UserName', max_length=100)),
                ('entrydate', models.DateField(db_column='EntryDate')),
                ('project', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Project', max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Category', max_length=100, null=True)),
                ('subcat', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='SubCat', max_length=100, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, db_column='StartDateTime', null=True)),
                ('startstatus', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='StartStatus', max_length=20, null=True)),
                ('description', models.TextField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Description', null=True)),
                ('enddatetime', models.DateTimeField(blank=True, db_column='EndDateTime', null=True)),
                ('endstatus', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='EndStatus', max_length=20, null=True)),
                ('duration', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Duration', max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('durationminutes', models.IntegerField(blank=True, db_column='DurationMinutes', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_cost.category_master')),
            ],
        ),
        migrations.CreateModel(
            name='task_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('assing_date', models.DateTimeField(auto_now_add=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_start_date', models.DateTimeField(blank=True, null=True)),
                ('task_end_date', models.DateTimeField(blank=True, null=True)),
                ('task_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=50)),
                ('task_duration', models.DurationField(blank=True, null=True)),
                ('task_status', models.CharField(default='Pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software_cost.project_master')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software_cost.user_master')),
            ],
        ),
        migrations.CreateModel(
            name='workentry_pause',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pause_start_time', models.DateTimeField()),
                ('pause_end_time', models.DateTimeField(blank=True, null=True)),
                ('pause_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_cost.workentry')),
            ],
        ),
    ]
