# Generated by Django 5.2.12 on 2026-08-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrsWorkentry',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='Latin1_General_CI_AI', db_column='UserName', max_length=100)),
                ('entrydate', models.DateField(db_column='EntryDate')),
                ('project', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Project', max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Category', max_length=100, null=True)),
                ('subcat', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='SubCat', max_length=100, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, db_column='StartDateTime', null=True)),
                ('startstatus', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='StartStatus', max_length=20, null=True)),
                ('description', models.TextField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Description', null=True)),
                ('enddatetime', models.DateTimeField(blank=True, db_column='EndDateTime', null=True)),
                ('endstatus', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='EndStatus', max_length=20, null=True)),
                ('duration', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Duration', max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('durationminutes', models.IntegerField(blank=True, db_column='DurationMinutes', null=True)),
            ],
            options={
                'db_table': 'Trs_Workentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='task_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('task_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
                ('user_status', models.BooleanField(default=True)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_cost.category_master')),
            ],
        ),
        migrations.CreateModel(
            name='project_task_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_cost.project_master')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_cost.task_master')),
            ],
        ),
        migrations.CreateModel(
            name='workentry_pause',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pause_start_time', models.DateTimeField()),
                ('pause_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_cost.trsworkentry')),
            ],
        ),
    ]
