# Generated by Django 6.0.7 on 2026-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_menu_permissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('menu_permissions', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
