# Generated by Django 5.2.12 on 2026-08-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_master',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software_cost.project_master'),
        ),
        migrations.AlterField(
            model_name='task_master',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_master',
            name='task_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
