# Generated by Django 6.0.7 on 2026-09-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0002_role_menu_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workentry',
            name='startstatus',
        ),
        migrations.AddField(
            model_name='workentry',
            name='task_id',
            field=models.ForeignKey(db_column='TaskID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='software_cost.task_master'),
        ),
    ]
