# Generated by Django 5.2.12 on 2026-08-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0002_task_master_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_master',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software_cost.user_master'),
        ),
    ]
