# Generated by Django 6.0.7 on 2026-09-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0003_remove_workentry_startstatus_workentry_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_master',
            name='task_status1',
            field=models.BooleanField(default=False),
        ),
    ]
