# Generated by Django 5.2.12 on 2026-08-31 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0003_task_master_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_master',
            name='assing_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
