# Generated by Django 6.0.7 on 2026-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0004_task_master_task_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='status',
            field=models.BooleanField(db_column='Status', default=False),
        ),
    ]
