# Generated by Django 6.0.7 on 2026-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0004_task_master_assing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry_pause',
            name='pause_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='project_task_mapping',
        ),
    ]
