# Generated by Django 5.2.12 on 2026-09-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0005_workentry_pause_pause_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_master',
            name='task_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task_master',
            name='task_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
