# Generated by Django 6.0.7 on 2026-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0005_workentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='workentry_images/'),
        ),
    ]
