# Generated by Django 6.0.7 on 2026-09-19 12:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0006_workentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/workentry_images_network/', location='\\\\10.1.21.11\\d\\workentry_images'), upload_to=''),
        ),
    ]
