# Generated by Django 6.0.7 on 2026-09-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0007_alter_workentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='user_status',
        ),
    ]
