# Generated by Django 6.0.7 on 2026-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0008_remove_user_master_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='user_status',
            field=models.BooleanField(default=True),
        ),
    ]
