# Generated by Django 6.0.7 on 2026-10-06 09:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_cost', '0009_user_master_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_master',
            name='task_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/workentry_images_network/', location='\\\\10.1.21.11\\d\\workentry_images'), upload_to=''),
        ),
    ]
