# Generated by Django 5.2.12 on 2026-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncfushion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridsetting',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
