# Generated by Django 5.2.12 on 2026-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncfushion', '0003_diwasg_diwasg_img_syncfushionkanban_syncfusiongantt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionrResult',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('result', models.JSONField(default=list)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('jobno', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Fashionr_result',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            sql="""
            IF NOT EXISTS (
                SELECT 1
                FROM sys.objects
                WHERE object_id = OBJECT_ID(N'[dbo].[syncfusion_blockeditor]')
                  AND type IN (N'U')
            )
            BEGIN
                CREATE TABLE [dbo].[syncfusion_blockeditor] (
                    [id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
                    [blocks] nvarchar(max) NOT NULL,
                    [created_at] datetime2 NOT NULL,
                    [updated_at] datetime2 NOT NULL
                );
            END
            """,
            reverse_sql="""
            IF OBJECT_ID(N'[dbo].[syncfusion_blockeditor]', N'U') IS NOT NULL
            BEGIN
                DROP TABLE [dbo].[syncfusion_blockeditor];
            END
            """,
        ),
        migrations.AddField(
            model_name='blockeditor',
            name='name',
            field=models.CharField(default=1, help_text='Name of the block template', max_length=50),
            preserve_default=False,
        ),
    ]
