# Generated by Django 5.2.12 on 2026-07-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncfushion', '0004_fashionrresult_blockeditor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAccinwpend',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(blank=True, max_length=450, null=True)),
                ('merch', models.CharField(blank=True, max_length=35, null=True)),
                ('orderno', models.CharField(blank=True, db_column='OrderNo', max_length=50, null=True)),
                ('no', models.IntegerField(db_column='No')),
                ('date', models.DateTimeField(db_column='Date')),
                ('duedate', models.DateTimeField(blank=True, db_column='DueDate', null=True)),
                ('dueday', models.IntegerField(blank=True, null=True)),
                ('orderdt', models.DateTimeField(blank=True, db_column='orderDt', null=True)),
                ('ordremday', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=35, null=True)),
                ('completed', models.SmallIntegerField(db_column='Completed')),
                ('ag', models.CharField(max_length=35)),
                ('an', models.CharField(max_length=35)),
                ('sz', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=173, null=True)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('inwqty', models.DecimalField(decimal_places=4, max_digits=38)),
                ('uom', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'view_accinwpend',
                'managed': False,
            },
        ),
    ]
