# Generated by Django 5.2.12 on 2026-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncfushion', '0005_viewaccinwpend'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpQms',
            fields=[
                ('sl', models.IntegerField(primary_key=True, serialize=False)),
                ('jobno', models.CharField(max_length=50)),
                ('pono', models.IntegerField()),
                ('acc_item', models.CharField(db_column='Acc_Item', max_length=80)),
                ('clr_siz', models.CharField(max_length=80)),
                ('retmark', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Tmp_Qms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewAccessoryDel',
            fields=[
                ('sl', models.IntegerField(primary_key=True, serialize=False)),
                ('jobno', models.CharField(max_length=50)),
                ('img', models.CharField(blank=True, max_length=539, null=True)),
                ('clrcombo', models.CharField(blank=True, max_length=150, null=True)),
                ('pono', models.IntegerField()),
                ('posupplier', models.CharField(max_length=80)),
                ('podate', models.CharField(max_length=50)),
                ('podue', models.CharField(max_length=50)),
                ('acc_item', models.CharField(db_column='Acc_Item', max_length=80)),
                ('clr_siz', models.CharField(max_length=80)),
                ('poqty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('uom', models.CharField(max_length=50)),
                ('inwarddate', models.CharField(max_length=50)),
                ('fddate', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('inwardqty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('inwpendqty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('inwdiffqty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('issueunit', models.CharField(max_length=80)),
                ('issuedt', models.CharField(max_length=50)),
                ('delqty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ret', models.DecimalField(decimal_places=2, max_digits=18)),
                ('storestock', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(max_length=13)),
                ('retmark', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'view_accessory_del',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCutBalpend',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('itemno', models.SmallIntegerField(db_column='ItemNo')),
                ('ordno', models.CharField(blank=True, max_length=50, null=True)),
                ('o_finaldelvdate', models.DateTimeField(blank=True, db_column='o_FinalDelvdate', null=True)),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('tbimg', models.CharField(blank=True, max_length=1550, null=True)),
                ('clr', models.CharField(blank=True, max_length=50, null=True)),
                ('siz', models.CharField(blank=True, max_length=50, null=True)),
                ('order_qty', models.IntegerField(blank=True, null=True)),
                ('rejection_qty', models.IntegerField(blank=True, null=True)),
                ('required_qty', models.IntegerField(blank=True, db_column='Required_Qty', null=True)),
                ('plan_qty', models.IntegerField(blank=True, db_column='Plan_Qty', null=True)),
                ('plan_bal_pers', models.DecimalField(blank=True, db_column='Plan_Bal_pers', decimal_places=2, max_digits=18, null=True)),
                ('actual_cut_qty', models.IntegerField(blank=True, db_column='Actual_Cut_Qty', null=True)),
                ('hand_cutting', models.IntegerField(blank=True, db_column='Hand_Cutting', null=True)),
                ('cutting_bal_pers', models.DecimalField(blank=True, db_column='Cutting_Bal_pers', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'view_cut_balpend',
                'managed': False,
            },
        ),
    ]
