# Generated by Django 6.0.7 on 2026-09-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncfushion', '0006_tmpqms_viewaccessorydel_viewcutbalpend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAccpopending',
            fields=[
                ('slno', models.BigIntegerField(db_column='Slno', primary_key=True, serialize=False)),
                ('pers', models.DecimalField(blank=True, db_column='Pers', decimal_places=6, max_digits=38, null=True)),
                ('orderno', models.CharField(db_column='OrderNo', max_length=50)),
                ('trsqty', models.DecimalField(db_column='TrsQty', decimal_places=4, max_digits=38)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('accessorygroupid', models.IntegerField(db_column='AccessoryGroupID')),
                ('accessoryid', models.IntegerField(db_column='AccessoryID')),
                ('colourid', models.IntegerField(db_column='ColourID')),
                ('accesizeid', models.IntegerField(db_column='AcceSizeID')),
                ('ordersizeid', models.IntegerField(db_column='OrderSizeID')),
                ('grp', models.CharField(db_column='Grp', max_length=35)),
                ('des', models.CharField(db_column='Des', max_length=35)),
                ('clr', models.CharField(db_column='Clr', max_length=50)),
                ('itemsiz', models.CharField(db_column='ItemSiz', max_length=50)),
                ('ordsiz', models.CharField(db_column='OrdSiz', max_length=35)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('uom', models.CharField(db_column='UOM', max_length=25)),
                ('supplier', models.CharField(db_column='Supplier', max_length=35)),
                ('phone1', models.CharField(db_column='Phone1', max_length=50)),
                ('contactperson', models.CharField(db_column='ContactPerson', max_length=35)),
                ('ratekg', models.DecimalField(db_column='RateKG', decimal_places=4, max_digits=19)),
                ('poqty', models.DecimalField(db_column='POQty', decimal_places=4, max_digits=38)),
                ('altquantity', models.DecimalField(db_column='AltQuantity', decimal_places=4, max_digits=18)),
                ('balpoqty', models.DecimalField(blank=True, db_column='BalPoQty', decimal_places=4, max_digits=38, null=True)),
                ('altuom', models.CharField(db_column='AltUOM', max_length=25)),
                ('img', models.CharField(blank=True, max_length=450, null=True)),
                ('ratealt', models.DecimalField(db_column='RateALT', decimal_places=4, max_digits=19)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('fdelvdate', models.DateTimeField(blank=True, db_column='o_FinalDelvdate', null=True)),
                ('ag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_accpopending',
                'managed': False,
            },
        ),
    ]
