# Generated by Django 5.2.12 on 2026-03-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herofashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='herofashion.submenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
