# Generated by Django 6.0.2 on 2026-02-26 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herofashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='menu_icons/'),
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herofashion.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herofashion.role')),
            ],
            options={
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
