# Generated by Django 6.0.2 on 2026-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herofashion', '0002_submenu_parent_alter_submenu_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='submenu',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
