# Generated by Django 6.0.2 on 2026-03-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herofashion', '0003_alter_submenu_options_submenu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_submenu',
            field=models.ForeignKey(blank=True, help_text='Select default submenu to open after login', null=True, on_delete=django.db.models.deletion.SET_NULL, to='herofashion.submenu'),
        ),
    ]
