# Generated by Django 5.2.12 on 2026-07-05 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_message_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
