# Generated by Django 5.2.12 on 2026-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundlereport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_date', models.DateTimeField(db_column='S_date')),
                ('job_no', models.CharField(db_collation='Latin1_General_CI_AI', max_length=50)),
                ('mbundle_id', models.CharField(db_collation='Latin1_General_CI_AI', max_length=50)),
                ('tb_name', models.CharField(db_collation='Latin1_General_CI_AI', max_length=100)),
                ('unit_id', models.CharField(max_length=100)),
                ('total_bundles', models.IntegerField()),
                ('pcs_count', models.IntegerField()),
                ('r_date', models.DateField(blank=True, db_column='r_Date', null=True)),
                ('scan', models.IntegerField()),
            ],
            options={
                'db_table': 'Unit_BundleReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasTopbottom',
            fields=[
                ('topbottom_des', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TopBottom_des', max_length=50, null=True)),
                ('topbottom_id', models.IntegerField(db_column='TopBottom_id', primary_key=True, serialize=False)),
                ('act', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('ty', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TY', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Mas_TopBottom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasUnit',
            fields=[
                ('unitcode', models.IntegerField(db_column='Unitcode', primary_key=True, serialize=False)),
                ('unitname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UnitName', max_length=50, null=True)),
                ('add1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Add1', max_length=50, null=True)),
                ('add2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Add2', max_length=50, null=True)),
                ('add3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Add3', max_length=50, null=True)),
                ('place', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Place', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Phone', max_length=50, null=True)),
                ('tinno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tinno', max_length=50, null=True)),
                ('cstno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('shortname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ShortName', max_length=10, null=True)),
                ('login', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('companyid', models.IntegerField(blank=True, null=True)),
                ('faxno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('essunit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Essunit', max_length=50, null=True)),
                ('outsideunit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OUTSIDEUNIT', max_length=1, null=True)),
                ('port', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('ty', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=3, null=True)),
                ('short', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=3, null=True)),
                ('dispid', models.IntegerField(blank=True, null=True)),
                ('pe', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('fabgdwn', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('div', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('staff', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Mas_Unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsCdelPcs1',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(db_column='Dt')),
                ('unitid', models.IntegerField(db_column='UnitID')),
                ('jobno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='JobNo', max_length=50)),
                ('tbid', models.IntegerField(db_column='TBID')),
                ('lcid', models.IntegerField(db_column='LcID')),
                ('totmastbdl', models.IntegerField(db_column='TotMastBdl')),
                ('totweight', models.DecimalField(db_column='Totweight', decimal_places=3, max_digits=18)),
                ('totbdl', models.IntegerField(db_column='Totbdl')),
                ('totpcs', models.IntegerField(db_column='Totpcs')),
                ('del_remarks', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Del_Remarks', max_length=80)),
                ('vechno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vechno', max_length=80)),
                ('ordsamid', models.IntegerField(db_column='OrdSamID')),
                ('cut_old', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trs_cdel_pcs1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsCdelPcs21',
            fields=[
                ('id', models.IntegerField(db_column='ID')),
                ('mbundid', models.IntegerField(db_column='MBundID')),
                ('mbappr', models.IntegerField(blank=True, null=True)),
                ('sl', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trs_cdel_pcs2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsCdelPcs3',
            fields=[
                ('sl', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='ID')),
                ('bdlid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BdlID', max_length=200)),
                ('sizid', models.IntegerField(db_column='SizID')),
                ('lotno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LotNo', max_length=10)),
                ('bdl', models.IntegerField(db_column='Bdl')),
                ('noofpcs', models.IntegerField(db_column='Noofpcs')),
                ('comboclr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('bundid', models.IntegerField(blank=True, null=True)),
                ('scan', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'trs_cdel_Pcs3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsMcutstickerprod',
            fields=[
                ('dt', models.DateTimeField(db_column='Dt')),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('mbud', models.IntegerField(db_column='Mbud')),
                ('bundid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BundID', max_length=200, primary_key=True, serialize=False)),
                ('jobno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='JobNo', max_length=50)),
                ('tbid', models.IntegerField(db_column='TBID')),
                ('comboclr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comboclr', max_length=50)),
                ('sizid', models.IntegerField(db_column='SIZID')),
                ('bdl', models.IntegerField(db_column='Bdl')),
                ('pc', models.IntegerField(db_column='Pc')),
                ('porid', models.IntegerField(db_column='PorID')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('bund_id', models.IntegerField(blank=True, null=True)),
                ('lotno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('hempid', models.IntegerField(blank=True, null=True)),
                ('frmbc', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('scan', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Trs_MCutStickerProd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unituser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('Unit-1', 'Unit-1'), ('Unit-2', 'Unit-2'), ('Unit-3', 'Unit-3'), ('Unit-4', 'Unit-4'), ('Unit-5', 'Unit-5')], max_length=20)),
                ('user_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'unit_unituser',
                'managed': False,
            },
        ),
    ]
