# Generated by Django 5.2.12 on 2026-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bundlereport',
            table='unit_bundlereport',
        ),
    ]
