"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--jpqy*__tak#1#7_0u^g5gt=n@rlpjvp5mstua5m^&i7+!8uad'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

# ALLOWED_HOSTS = ['hfapi.herofashion.com','10.1.21.153','localhost','127.0.0.1','10.1.21.13','10.1.21.154','10.1.21.110']
ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://hf.herofashion.com",
    "https://web.herofashion.com",
    "https://hf.herofashion.com",
    "https://hfapi.herofashion.com",
    "https://sync.herofashion.com",
    "https://dev.herofashion.com",
    "http://10.1.21.80:3600",
    "https://hfempdtls.netlify.app",
    "http://10.1.21.110:7003",
    
]

CSRF_TRUSTED_ORIGINS = [
    "http://10.1.21.158:3000/",
    "http://localhost:3000",
    "http://10.1.21.110:7003",
    "https://hf.herofashion.com",
    "https://hfapi.herofashion.com",
    "https://sync.herofashion.com",
    "https://web.herofashion.com",
    "https://dev.herofashion.com",
    "https://hfempdtls.netlify.app",
    "http://10.1.21.110:7003",
    
]
# settings.py

CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
CSRF_COOKIE_SECURE = not DEBUG

SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
SESSION_COOKIE_SECURE = not DEBUG


APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist', 
    'rest_framework',
    'django_filters',
    'corsheaders',
    'herofashion',
    'qcapp',
    'syncfushion',
    'advance',
    'reports',
    'bit_checking',
    'imp_reports',
    # 'chat',
    'chat_app',
    'chatbot',
    "channels",
    'n8n',
    'dc_app',
    'bundle_tracking',
    'production_live_scan',
    'fashionr',
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 200
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 200

X_FRAME_OPTIONS = 'ALLOWALL'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# if DEBUG:
#     SECURE_CROSS_ORIGIN_OPENER_POLICY = None
# else:
#     SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

DEBUG = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'herofashion.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
     'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer', # ஒருவேளை ப்ரொடக்ஷன் போனால் 'channels_redis.core.RedisChannelLayer' ஆக மாற்றவும்
    },
}
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'hfapi',
        'USER': 'sa',
        'PASSWORD': 'Fashion@01',
        'HOST': '10.1.21.11',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': "yes"
        },
        'CONN_MAX_AGE': 300,
    },

    'demo': {
        'ENGINE': 'mssql',
        'NAME': 'Tally2sql',
        'USER': 'sa',
        'PASSWORD': 'Fashion@01',
        'HOST': '10.1.21.11',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': "yes"
        },
        'CONN_MAX_AGE': 300,
    },
    'main': {
        'ENGINE': 'mssql',
        'NAME': 'Garmentrk',
        'USER': 'sa',
        'PASSWORD': 'Fashion@01',
        'HOST': '10.1.21.11',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': "yes"
        },
        'CONN_MAX_AGE': 300,
    },
    'mssql1' : {
        'ENGINE': 'mssql',
        'NAME': 'demo',
        'USER': 'sa',
        'PASSWORD': 'Fashion@01',
        'HOST': '10.1.21.11',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            },
        'CONN_MAX_AGE': 300,
    },
     'app' : {
        'ENGINE': 'mssql',
        'NAME': 'Django',
        'USER': 'sa',
        'PASSWORD': 'Fashion@01',
        'HOST': '10.1.21.11',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            },
        'CONN_MAX_AGE': 300,
    },
     'demo1': {
            'ENGINE': 'mssql',
            'NAME': 'NewPowerBi',
            'USER': 'sa',
            'PASSWORD': 'Fashion@01',
            'HOST': '10.1.21.11',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            },
            'CONN_MAX_AGE': 300,
    },
    'test': {
            'ENGINE': 'mssql',
            'NAME': 'testerphero',
            'USER': 'sa',
            'PASSWORD': 'Fashion@01',
            'HOST': '10.1.21.11',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'trusted_connection': "yes"
            },
            'CONN_MAX_AGE': 300,
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False
# USE_TZ = True



STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STAFF_IMAGES_URL = '/staff_images/'
STAFF_IMAGES_ROOT = r'\\10.1.21.11\d\Staff_Employee_Images'

PDF_STORAGE_PATH = r"\\adminserver\File Sharing\AAAA Hero\Syncfusion Pdf Reports"

# Email configurationcmd


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hfautomation2026@gmail.com'
EMAIL_HOST_PASSWORD = 'uoea lfup fncv uxyv'   


DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Bold Reports configuration (Application-level)
BOLD_REPORTS = {
    "URL": "https://api.herofashion.com",
    "SITE_IDENTIFIER": "site3",
    "USER_EMAIL": "admin@veahtech.com",
    "EMBED_SECRET_KEY": "RMkS8LRS119c632BGyGeScftReTRIRI",
}


# LOGIN_URL = '/chat/login/'
# LOGIN_REDIRECT_URL = '/chat/'
# LOGOUT_REDIRECT_URL = '/chat/login/'
ASGI_APPLICATION = 'backend.asgi.application'
