# Generated by Django 5.2.12 on 2026-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcheckingPlyDetails',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(db_column='Emp_id')),
                ('qr_id', models.IntegerField(db_column='Qr_id')),
                ('total_pcs', models.IntegerField(db_column='Total_pcs')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('result', models.CharField(blank=True, db_column='Result', max_length=200, null=True)),
                ('final_tpcs', models.CharField(blank=True, db_column='Final_tpcs', max_length=50, null=True)),
                ('out_ply', models.CharField(blank=True, db_column='Out_ply', max_length=100, null=True)),
                ('ok_pcs', models.CharField(blank=True, db_column='Ok_pcs', max_length=50, null=True)),
                ('mistake_pcs', models.CharField(blank=True, db_column='Mistake_pcs', max_length=50, null=True)),
                ('mistake_ply', models.CharField(blank=True, db_column='Mistake_ply', max_length=100, null=True)),
                ('r_p', models.BooleanField(default=False)),
                ('entry_mode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('typ', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TYP', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Bitchecking_ply_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stickemp',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=4000, null=True)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('photo', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'stickemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsCutstickerprodNew',
            fields=[
                ('dt', models.DateTimeField(db_column='Dt')),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('qrid', models.IntegerField(db_column='QrID', primary_key=True, serialize=False)),
                ('jobno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='JobNo', max_length=50)),
                ('tbid', models.IntegerField(db_column='TBID')),
                ('comboclr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comboclr', max_length=50)),
                ('sizid', models.IntegerField(db_column='SIZID')),
                ('planno', models.IntegerField(db_column='Planno')),
                ('plansl', models.IntegerField(db_column='Plansl')),
                ('pc', models.IntegerField(db_column='Pc')),
                ('lotno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LotNo', max_length=50)),
                ('ratio', models.IntegerField(blank=True, db_column='Ratio', null=True)),
                ('porid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trs_CutStickerProd_New',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsCutstickerprodNew1',
            fields=[
                ('t', models.CharField(db_column='T', max_length=50)),
                ('qrid', models.IntegerField(db_column='QRID', primary_key=True, serialize=False)),
                ('planno', models.IntegerField()),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('topbott_id', models.IntegerField(db_column='TopBott_ID')),
                ('clrcombo', models.CharField(db_column='Clrcombo', max_length=80)),
                ('lotno', models.CharField(db_column='LotNo', max_length=50)),
                ('plansl', models.IntegerField(db_column='Plansl')),
                ('sizeid', models.IntegerField(db_column='SizeID')),
                ('ratio', models.IntegerField(db_column='Ratio')),
                ('pc', models.IntegerField(db_column='Pc')),
                ('porid', models.IntegerField(blank=True, null=True)),
                ('portion_des', models.CharField(db_column='PORTION_DES', max_length=50)),
            ],
            options={
                'db_table': 'Trs_CutStickerProd_New1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsStickerdtls',
            fields=[
                ('planno', models.IntegerField()),
                ('sl', models.IntegerField(primary_key=True, serialize=False)),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('topbott_id', models.IntegerField(db_column='TopBott_ID')),
                ('clrcombo', models.CharField(db_column='Clrcombo', max_length=80)),
                ('colour', models.IntegerField(db_column='Colour')),
                ('lotno', models.CharField(db_column='LotNo', max_length=50)),
                ('sc', models.CharField(db_column='SC', max_length=1)),
                ('plansl', models.IntegerField(db_column='Plansl')),
                ('sizeid', models.IntegerField(db_column='SizeID')),
                ('ratio', models.IntegerField(db_column='Ratio')),
                ('pc', models.IntegerField(db_column='Pc')),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('size', models.CharField(db_column='Size', max_length=35)),
                ('portion_des', models.CharField(db_column='PORTION_DES', max_length=50)),
                ('porid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trs_StickerDtls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueMistakePartDetails',
            fields=[
                ('rownum', models.BigIntegerField(db_column='RowNum', primary_key=True, serialize=False)),
                ('qrid', models.IntegerField(db_column='QrID')),
                ('planno', models.IntegerField(db_column='Planno')),
                ('jobno', models.CharField(max_length=50)),
                ('markerno', models.IntegerField(db_column='Markerno')),
                ('det_main_part', models.CharField(blank=True, max_length=50, null=True)),
                ('det_part', models.CharField(blank=True, max_length=70, null=True)),
                ('topbottom_id', models.IntegerField(db_column='TopBottom_id')),
            ],
            options={
                'db_table': 'vue_mistake_part_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bit_checking_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaner_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('descriptions', models.CharField(max_length=50)),
                ('out_pcs', models.TextField()),
                ('mistake_pcs', models.TextField()),
                ('out_pcs_count', models.IntegerField()),
                ('ok_pcs', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan_no', models.IntegerField()),
                ('total_select_pcs', models.TextField()),
                ('entry_mood', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bit_start_end_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrid', models.IntegerField()),
                ('empid', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
