# Generated by Django 6.0.2 on 2026-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stickemp',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=4000, null=True)),
                ('employee', models.CharField(blank=True, db_column='Employee', max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('photo', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'stickemp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsStickerdtls',
            fields=[
                ('planno', models.IntegerField()),
                ('sl', models.IntegerField(primary_key=True, serialize=False)),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('topbott_id', models.IntegerField(db_column='TopBott_ID')),
                ('clrcombo', models.CharField(db_column='Clrcombo', max_length=80)),
                ('colour', models.IntegerField(db_column='Colour')),
                ('lotno', models.CharField(db_column='LotNo', max_length=50)),
                ('sc', models.CharField(db_column='SC', max_length=1)),
                ('plansl', models.IntegerField(db_column='Plansl')),
                ('sizeid', models.IntegerField(db_column='SizeID')),
                ('ratio', models.IntegerField(db_column='Ratio')),
                ('pc', models.IntegerField(db_column='Pc')),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('size', models.CharField(db_column='Size', max_length=35)),
                ('portion_des', models.CharField(db_column='PORTION_DES', max_length=50)),
                ('porid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trs_StickerDtls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueMistakePartDetails',
            fields=[
                ('rownum', models.BigIntegerField(db_column='RowNum', primary_key=True, serialize=False)),
                ('planno', models.IntegerField(db_column='Planno')),
                ('jobno', models.CharField(max_length=50)),
                ('markerno', models.IntegerField(db_column='Markerno')),
                ('det_main_part', models.CharField(blank=True, max_length=50, null=True)),
                ('det_part', models.CharField(blank=True, max_length=70, null=True)),
                ('topbottom_id', models.IntegerField(db_column='TopBottom_id')),
            ],
            options={
                'db_table': 'vue_mistake_part_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bit_checking_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaner_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('descriptions', models.CharField(max_length=50)),
                ('select_pcs', models.TextField()),
                ('mistake_pcs', models.TextField()),
                ('out_pcs', models.IntegerField()),
                ('ok_pcd', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan_no', models.IntegerField()),
                ('total_select_pcs', models.TextField()),
            ],
        ),
    ]
