# Generated by Django 5.2.12 on 2026-06-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0001_initial'),
    ]

    operations = [
    ]
