# Generated by Django 6.0.2 on 2026-05-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bit_checking_updates',
            old_name='ok_pcd',
            new_name='ok_pcs',
        ),
        migrations.RemoveField(
            model_name='bit_checking_updates',
            name='select_pcs',
        ),
    ]
