# Generated by Django 5.2.12 on 2026-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0002_add_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bit_checking_updates',
            name='type',
        ),
        migrations.AddField(
            model_name='bit_checking_updates',
            name='types',
            field=models.CharField(blank=True, db_collation='Latin1_General_CI_AI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bit_start_end_time',
            name='types',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
