# Generated by Django 6.0.2 on 2026-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0002_rename_ok_pcd_bit_checking_updates_ok_pcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit_checking_updates',
            name='out_pcs_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bit_checking_updates',
            name='out_pcs',
            field=models.TextField(),
        ),
    ]
