# Generated by Django 5.2.12 on 2026-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0002_add_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit_checking_updates',
            name='types',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
