# Generated by Django 5.2.12 on 2026-07-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0003_remove_bit_checking_updates_type_and_more'),
    ]

    operations = [
    ]
