# Generated by Django 6.0.2 on 2026-05-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0003_bit_checking_updates_out_pcs_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcheckingPlyDetails',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(db_column='Emp_id')),
                ('qr_id', models.IntegerField(db_column='Qr_id')),
                ('total_pcs', models.IntegerField(db_column='Total_pcs')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('result', models.CharField(blank=True, db_column='Result', max_length=200, null=True)),
                ('final_tpcs', models.CharField(blank=True, db_column='Final_tpcs', max_length=50, null=True)),
                ('out_ply', models.CharField(blank=True, db_column='Out_ply', max_length=100, null=True)),
                ('ok_pcs', models.CharField(blank=True, db_column='Ok_pcs', max_length=50, null=True)),
                ('mistake_pcs', models.CharField(blank=True, db_column='Mistake_pcs', max_length=50, null=True)),
                ('mistake_ply', models.CharField(blank=True, db_column='Mistake_ply', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Bitchecking_ply_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsCutstickerprodNew',
            fields=[
                ('dt', models.DateTimeField(db_column='Dt')),
                ('empid', models.IntegerField(db_column='EmpID')),
                ('qrid', models.IntegerField(db_column='QrID', primary_key=True, serialize=False)),
                ('jobno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='JobNo', max_length=50)),
                ('tbid', models.IntegerField(db_column='TBID')),
                ('comboclr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comboclr', max_length=50)),
                ('sizid', models.IntegerField(db_column='SIZID')),
                ('planno', models.IntegerField(db_column='Planno')),
                ('plansl', models.IntegerField(db_column='Plansl')),
                ('pc', models.IntegerField(db_column='Pc')),
                ('lotno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LotNo', max_length=50)),
                ('ratio', models.IntegerField(blank=True, db_column='Ratio', null=True)),
                ('porid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trs_CutStickerProd_New',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='qc_start_end_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrid', models.IntegerField()),
                ('empid', models.IntegerField()),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
