# Generated by Django 5.2.12 on 2026-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0003_bit_checking_updates_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bit_checking_updates',
            name='type',
        ),
        migrations.AlterField(
            model_name='bit_checking_updates',
            name='types',
            field=models.CharField(blank=True, db_collation='Latin1_General_CI_AI', max_length=50, null=True),
        ),
    ]
