# Generated by Django 6.0.2 on 2026-05-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0004_bitcheckingplydetails_trscutstickerprodnew_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qc_start_end_time',
            new_name='bit_start_end_time',
        ),
    ]
