# Generated by Django 6.0.2 on 2026-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0005_rename_qc_start_end_time_bit_start_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bit_start_end_time',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
