# Generated by Django 5.2.12 on 2026-08-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_checking', '0005_alter_bit_start_end_time_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAccinwardVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.BigIntegerField(blank=True, db_column='SlNo', null=True)),
                ('date', models.DateTimeField(db_column='Date')),
                ('record_pk', models.CharField(blank=True, db_column='pk', max_length=319, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=35, null=True)),
                ('supplierdcno', models.CharField(db_column='SupplierDCNo', max_length=50)),
                ('pono', models.IntegerField(blank=True, db_column='PONo', null=True)),
                ('jobno', models.CharField(blank=True, db_column='JobNo', max_length=50, null=True)),
                ('items', models.CharField(blank=True, db_column='Items', max_length=71, null=True)),
                ('clr_siz', models.CharField(max_length=101)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('uom', models.CharField(db_column='UOM', max_length=25)),
                ('bill_rate', models.DecimalField(blank=True, db_column='Bill_Rate', decimal_places=4, max_digits=19, null=True)),
                ('gst', models.CharField(blank=True, db_column='GST', max_length=50, null=True)),
                ('billno', models.CharField(blank=True, db_column='BillNo', max_length=50, null=True)),
                ('billdate', models.DateTimeField(blank=True, db_column='BillDate', null=True)),
            ],
            options={
                'db_table': 'view_accinward_verification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accessory_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_name', models.CharField(blank=True, max_length=400, null=True)),
                ('verify1', models.BooleanField(default=False)),
                ('verify2', models.BooleanField(default=False)),
                ('verify1_date', models.DateTimeField(blank=True, null=True)),
                ('verify2_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_accessory_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('verify1', models.BooleanField(default=False)),
                ('verify2', models.BooleanField(default=False)),
            ],
        ),
    ]
