# Generated by Django 6.0.7 on 2026-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillAge',
            fields=[
                ('no', models.IntegerField(db_column='No', primary_key=True, serialize=False)),
                ('edate', models.DateTimeField(db_column='EDate')),
                ('billdate', models.DateTimeField(db_column='BillDate')),
                ('billno', models.CharField(blank=True, db_column='BillNo', max_length=63, null=True)),
                ('narration', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=35, null=True)),
                ('module', models.CharField(blank=True, db_column='Module', max_length=50, null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=12, null=True)),
                ('ageing', models.IntegerField(blank=True, db_column='Ageing', null=True)),
                ('suppliers', models.CharField(blank=True, db_column='Suppliers', max_length=35, null=True)),
                ('employees', models.CharField(blank=True, db_column='Employees', max_length=35, null=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=4, max_digits=19)),
                ('billpassed', models.SmallIntegerField(db_column='BillPassed')),
            ],
            options={
                'db_table': 'bill_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillMdapprove',
            fields=[
                ('billpaid', models.SmallIntegerField(db_column='BillPaid')),
                ('billpassed', models.SmallIntegerField(db_column='BillPassed')),
                ('lz_module_name11', models.CharField(blank=True, db_column='LZ_Module Name11', max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=35, null=True)),
                ('company_name', models.CharField(blank=True, db_column='Company_Name', max_length=50, null=True)),
                ('billno', models.CharField(max_length=50)),
                ('billno1', models.CharField(blank=True, db_column='Billno1', max_length=63, null=True)),
                ('supplier', models.CharField(blank=True, db_column='Supplier', max_length=35, null=True)),
                ('edate', models.DateTimeField(db_column='EDate')),
                ('billdate', models.DateTimeField(db_column='BillDate')),
                ('lz_module_name1', models.CharField(blank=True, db_column='LZ_Module Name1', max_length=50, null=True)),
                ('field_rowdata', models.IntegerField(db_column='_ROWDATA', primary_key=True, serialize=False)),
                ('lz_no', models.IntegerField(blank=True, db_column='LZ_No', null=True)),
                ('mdapproval', models.CharField(blank=True, db_column='MDApproval', max_length=12, null=True)),
                ('hz_version', models.IntegerField(blank=True, db_column='HZ_Version', null=True)),
                ('le_date', models.DateTimeField(blank=True, db_column='LE_Date', null=True)),
                ('lz_reference', models.CharField(blank=True, db_column='LZ_Reference', max_length=50, null=True)),
                ('lz_beno', models.IntegerField(blank=True, db_column='LZ_BENo', null=True)),
                ('le_bedate', models.DateTimeField(blank=True, db_column='LE_BEDate', null=True)),
                ('lz_module_name', models.IntegerField(blank=True, db_column='LZ_Module Name', null=True)),
                ('lz_supplier', models.CharField(blank=True, db_column='LZ_Supplier', max_length=35, null=True)),
                ('lz_billno', models.CharField(blank=True, db_column='LZ_BillNo', max_length=50, null=True)),
                ('le_billdate', models.DateTimeField(blank=True, db_column='LE_BillDate', null=True)),
                ('ra_assessable_amount', models.DecimalField(blank=True, db_column='RA_Assessable Amount', decimal_places=4, max_digits=19, null=True)),
                ('ra_taxableocamount', models.DecimalField(blank=True, db_column='RA_TaxableOCAmount', decimal_places=4, max_digits=19, null=True)),
                ('ra_nontaxableocamount', models.DecimalField(blank=True, db_column='RA_NonTaxableOCAmount', decimal_places=4, max_digits=19, null=True)),
                ('ra_billvalue', models.DecimalField(blank=True, db_column='RA_BillValue', decimal_places=4, max_digits=19, null=True)),
                ('ra_tds_deducted_amount', models.DecimalField(blank=True, db_column='RA_TDS Deducted Amount', decimal_places=4, max_digits=19, null=True)),
                ('ra_bill_pass_value', models.DecimalField(blank=True, db_column='RA_Bill Pass Value', decimal_places=4, max_digits=19, null=True)),
                ('lz_isauthorized_field', models.CharField(blank=True, db_column='LZ_isAuthorized?', max_length=13, null=True)),
                ('lz_incharge', models.CharField(blank=True, db_column='LZ_Incharge', max_length=35, null=True)),
            ],
            options={
                'db_table': 'Bill_mdapprove',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillPass',
            fields=[
                ('no', models.IntegerField(db_column='No', primary_key=True, serialize=False)),
                ('edate', models.DateTimeField(blank=True, db_column='EDate', null=True)),
                ('billdate', models.DateTimeField(db_column='BillDate')),
                ('billno', models.CharField(blank=True, db_column='BillNo', max_length=63, null=True)),
                ('billno1', models.CharField(max_length=50)),
                ('paymentdate', models.DateTimeField(blank=True, null=True)),
                ('daysbetweenbillandpayment', models.IntegerField(blank=True, db_column='DaysBetweenBillAndPayment', null=True)),
                ('module1', models.CharField(blank=True, db_column='Module1', max_length=50, null=True)),
                ('paymentstatus', models.CharField(blank=True, db_column='PaymentStatus', max_length=6, null=True)),
                ('ageing', models.IntegerField(blank=True, db_column='Ageing', null=True)),
                ('daysbetweenbillandedate', models.IntegerField(blank=True, db_column='DaysBetweenBillAndEDate', null=True)),
                ('module', models.CharField(blank=True, db_column='Module', max_length=255, null=True)),
                ('suppliers', models.CharField(blank=True, db_column='Suppliers', max_length=35, null=True)),
                ('employees', models.CharField(blank=True, db_column='Employees', max_length=35, null=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=4, max_digits=19)),
                ('billpassed', models.SmallIntegerField(db_column='BillPassed')),
                ('br_ageing', models.IntegerField(blank=True, db_column='BR Ageing', null=True)),
                ('billdate_ageing', models.IntegerField(blank=True, db_column='BillDate Ageing', null=True)),
            ],
            options={
                'db_table': 'Bill_pass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holdwagepaid',
            fields=[
                ('entry_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dt', models.DateField()),
                ('aadhar_no', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('emp_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('t_period', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('paid_amt', models.DecimalField(decimal_places=0, max_digits=18)),
                ('remarks', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'trs_holdwagepaid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueHoldwage',
            fields=[
                ('rownum', models.BigIntegerField(db_column='RowNum', primary_key=True, serialize=False)),
                ('accountdetails1', models.CharField(blank=True, db_column='Accountdetails1', max_length=200, null=True)),
                ('code', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(db_column='Period', max_length=50)),
                ('holdamount', models.DecimalField(db_column='HoldAmount', decimal_places=2, max_digits=18)),
                ('chold', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tot', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'vue_holdwage',
                'managed': False,
            },
        ),
    ]
