# Generated by Django 5.2.12 on 2026-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcadminmistake',
            name='category',
            field=models.CharField(choices=[('Minor Defects', 'Minor Defects'), ('Major Defects', 'Major Defects'), ('Critical Defects', 'Critical Defects')], max_length=50),
        ),
    ]
