# Generated by Django 5.2.12 on 2026-03-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0002_alter_qcadminmistake_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcadminmistake',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
