# Generated by Django 5.2.12 on 2026-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0004_unit_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='qc_piece_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_no', models.CharField(max_length=20)),
                ('jobno', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('total_pieces', models.IntegerField()),
                ('piece_no', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('mistake_name', models.CharField(max_length=50)),
                ('mistake_count', models.IntegerField()),
            ],
        ),
    ]
