# Generated by Django 5.2.12 on 2026-03-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0005_qc_piece_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_piece_data',
            name='bundle_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
