# Generated by Django 5.2.12 on 2026-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0006_qc_piece_data_bundle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_piece_data',
            name='mistake_percentage',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qc_piece_data',
            name='total_mistake',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
