# Generated by Django 5.2.12 on 2026-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0007_qc_piece_data_mistake_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qc_piece_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_no', models.CharField(max_length=20)),
                ('bundle_id', models.CharField(max_length=20)),
                ('jobno', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('total_pieces', models.IntegerField()),
                ('checked_piece', models.IntegerField()),
                ('force_save', models.BooleanField(default=False)),
            ],
        ),
    ]
