# Generated by Django 5.2.12 on 2026-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0008_qc_piece_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_piece_data',
            name='line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qc_piece_data',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qc_piece_final',
            name='line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qc_piece_final',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
