# Generated by Django 5.2.12 on 2026-03-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0009_qc_piece_data_line_qc_piece_data_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identity', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
