# Generated by Django 5.2.12 on 2026-03-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0010_machine_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.line')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='qcapp.machine_details')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('machine',), name='one_machine_one_line')],
            },
        ),
    ]
