# Generated by Django 5.2.12 on 2026-03-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0011_machineallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineallocation',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qcapp.line'),
        ),
        migrations.AlterField(
            model_name='machineallocation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='qcapp.machine_details'),
        ),
        migrations.AlterField(
            model_name='machineallocation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qcapp.unit'),
        ),
    ]
