# Generated by Django 5.2.12 on 2026-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0013_empwisesal_emp_allocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_allocate',
            name='ststus',
            field=models.BooleanField(default=False),
        ),
    ]
