# Generated by Django 5.2.12 on 2026-03-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0014_emp_allocate_ststus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_allocate',
            old_name='ststus',
            new_name='status',
        ),
    ]
