# Generated by Django 5.2.12 on 2026-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0015_rename_ststus_emp_allocate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueProcessSequence',
            fields=[
                ('jobno', models.CharField(db_column='JOBNO', max_length=50)),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('slno', models.BigIntegerField(blank=True, null=True)),
                ('tbid', models.IntegerField(db_column='TBID')),
                ('trn', models.CharField(db_column='TRN', max_length=1)),
                ('sl', models.IntegerField(db_column='SL', primary_key=True, serialize=False)),
                ('sl1', models.IntegerField(db_column='SL1')),
                ('prsid', models.IntegerField(db_column='PRSID')),
                ('process_des', models.CharField(blank=True, db_column='Process_des', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Vue_Process_Sequence',
                'managed': False,
            },
        ),
    ]
