# Generated by Django 5.2.12 on 2026-03-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0016_vueprocesssequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_piece_data',
            name='qc_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qc_piece_final',
            name='qc_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
