# Generated by Django 5.2.12 on 2026-03-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0017_qc_piece_data_qc_type_qc_piece_final_qc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineallocation',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.line'),
        ),
        migrations.AlterField(
            model_name='machineallocation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='qcapp.machine_details'),
        ),
        migrations.AlterField(
            model_name='machineallocation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.unit'),
        ),
    ]
