# Generated by Django 5.2.12 on 2026-03-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0018_alter_machineallocation_line_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='machineallocation',
            name='one_machine_one_line',
        ),
    ]
