# Generated by Django 6.0.2 on 2026-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0019_remove_machineallocation_one_machine_one_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_details',
            name='mcgrp',
            field=models.CharField(blank=True, db_column='MCGRP', max_length=50, null=True),
        ),
    ]
