# Generated by Django 6.0.2 on 2026-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0020_machine_details_mcgrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_details',
            name='mcgrp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
