# Generated by Django 6.0.2 on 2026-03-31 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0021_alter_machine_details_mcgrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='roving_qc_mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=20)),
                ('operation', models.CharField(max_length=100)),
                ('emb_id', models.CharField(max_length=20)),
                ('shade_var', models.BooleanField(default=False)),
                ('num_sticker', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qc_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roving_mistakes', to='qcapp.qc_piece_data')),
            ],
        ),
    ]
