# Generated by Django 6.0.2 on 2026-04-03 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0022_roving_qc_mistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_piece_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='qc_piece_data',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qc_piece_final',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='qc_piece_final',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
