# Generated by Django 6.0.2 on 2026-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0023_qc_piece_data_date_qc_piece_data_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_allocate',
            name='seq',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
