# Generated by Django 6.0.2 on 2026-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0025_alter_emp_allocate_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('wunit', models.CharField(blank=True, db_column='Wunit', max_length=70, null=True)),
                ('cat', models.CharField(blank=True, max_length=70, null=True)),
                ('photo', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'vue_user',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='qc_piece_final',
            name='seq',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
