# Generated by Django 6.0.2 on 2026-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0026_vueuser_qc_piece_final_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_piece_final',
            name='machine_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
