# Generated by Django 6.0.2 on 2026-04-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0028_qc_piece_data_machine_id_qc_piece_data_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qc_piece_data',
            name='machine_id',
        ),
        migrations.RemoveField(
            model_name='qc_piece_data',
            name='seq',
        ),
        migrations.AddField(
            model_name='roving_qc_mistake',
            name='seq',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
