# Generated by Django 6.0.2 on 2026-04-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0029_remove_qc_piece_data_machine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_piece_data',
            name='machine_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qc_piece_data',
            name='seq',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
