# Generated by Django 6.0.2 on 2026-04-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0030_qc_piece_data_machine_id_qc_piece_data_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mas_contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cont_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('con_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.mas_contractor')),
            ],
        ),
    ]
