# Generated by Django 6.0.2 on 2026-04-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0031_mas_contractor_cont_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needle_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
