# Generated by Django 6.0.2 on 2026-04-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0032_needle_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='needle_change',
            name='n_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
