# Generated by Django 6.0.2 on 2026-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0033_needle_change_n_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='cut_sample_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.CharField(max_length=50)),
                ('bundle_no', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('measurement_dtls', models.CharField(max_length=100)),
                ('measurement', models.IntegerField()),
                ('reading1', models.IntegerField()),
                ('reading2', models.IntegerField()),
                ('reading3', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bf_ironing', models.BooleanField(default=False)),
                ('af_ironing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='cut_sample_data_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.CharField(max_length=50)),
                ('bundle_no', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bf_ironing', models.BooleanField(default=False)),
                ('af_ironing', models.BooleanField(default=False)),
            ],
        ),
    ]
