# Generated by Django 6.0.2 on 2026-04-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0034_cut_sample_data_cut_sample_data_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut_sample_data',
            name='measurement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cut_sample_data',
            name='reading1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cut_sample_data',
            name='reading2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cut_sample_data',
            name='reading3',
            field=models.CharField(max_length=50),
        ),
    ]
