# Generated by Django 6.0.2 on 2026-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0035_alter_cut_sample_data_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut_sample_data',
            name='pcs_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
