# Generated by Django 6.0.2 on 2026-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0036_cut_sample_data_pcs_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut_sample_data',
            old_name='pcs_no',
            new_name='pcs_no_r1',
        ),
        migrations.AddField(
            model_name='cut_sample_data',
            name='pcs_no_r2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cut_sample_data',
            name='pcs_no_r3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
