# Generated by Django 6.0.2 on 2026-04-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0037_rename_pcs_no_cut_sample_data_pcs_no_r1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut_sample_data',
            name='pcs_no_r1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cut_sample_data',
            name='pcs_no_r2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cut_sample_data',
            name='pcs_no_r3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
