# Generated by Django 6.0.2 on 2026-04-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0038_alter_cut_sample_data_pcs_no_r1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut_sample_data',
            name='reading1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cut_sample_data',
            name='reading2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cut_sample_data',
            name='reading3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
