# Generated by Django 6.0.2 on 2026-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0039_alter_cut_sample_data_reading1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut_sample_data_final',
            name='force_save',
            field=models.BooleanField(default=False),
        ),
    ]
