# Generated by Django 6.0.2 on 2026-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0040_cut_sample_data_final_force_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut_sample_data',
            name='bundle_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cut_sample_data_final',
            name='bundle_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
