# Generated by Django 5.2.12 on 2026-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0041_cut_sample_data_bundle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roving_qc_mistake',
            name='emb_id',
            field=models.CharField(max_length=100),
        ),
    ]
