# Generated by Django 6.0.2 on 2026-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0042_alter_roving_qc_mistake_emb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_allocate',
            name='jobno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_allocate',
            name='top_bottom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
