# Generated by Django 5.2.12 on 2026-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0043_emp_allocate_jobno_emp_allocate_top_bottom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont_employee',
            name='code',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='emp_allocate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mas_contractor',
            name='code',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
