# Generated by Django 5.2.12 on 2026-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0044_alter_cont_employee_code_alter_emp_allocate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_allocate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
