# Generated by Django 5.2.12 on 2026-06-19 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0045_alter_emp_allocate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_allocate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
