# Generated by Django 5.2.12 on 2026-06-19 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0046_alter_emp_allocate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='sequency_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(blank=True, max_length=100, null=True)),
                ('jobno', models.CharField(blank=True, max_length=100, null=True)),
                ('top_bottom', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('emp_allocate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='qcapp.emp_allocate')),
            ],
        ),
    ]
