# Generated by Django 5.2.12 on 2026-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0047_sequency_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_allocate',
            name='seq',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
