# Generated by Django 5.2.12 on 2026-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0048_alter_emp_allocate_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcadminmistake',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
