# Generated by Django 5.2.12 on 2026-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0049_qcadminmistake_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcadminmistake',
            name='department',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('dyeing', 'Dyeing'), ('knitting', 'Knitting'), ('cutting', 'Cutting'), ('printing', 'Printing'), ('sewing', 'Sewing'), ('trimming_checking', 'Trimming & Checking'), ('accessories', 'Accessories')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qcadminmistake',
            name='category',
            field=models.CharField(choices=[('Minor Defects', 'Minor Defects'), ('Major Defects', 'Major Defects'), ('Critical Defects', 'Critical Defects'), ('rowing_qc', 'Rowing QC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='qcadminmistake',
            name='code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='qcadminmistake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qc_admin_mistakes/'),
        ),
    ]
