# Generated by Django 5.2.12 on 2026-07-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0050_qcadminmistake_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qc_hourly_approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('line', models.IntegerField()),
                ('approval_hour', models.IntegerField()),
                ('date', models.DateField()),
                ('unit_incharge_user', models.IntegerField(null=True)),
                ('unit_incharge_sign', models.ImageField(null=True, upload_to='digital_sign/')),
                ('unit_incharge_time', models.DateTimeField(null=True)),
                ('oa_user', models.IntegerField(null=True)),
                ('oa_sign', models.ImageField(null=True, upload_to='digital_sign/')),
                ('oa_time', models.DateTimeField(null=True)),
                ('fm_user', models.IntegerField(null=True)),
                ('fm_sign', models.ImageField(null=True, upload_to='digital_sign/')),
                ('fm_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('unit', 'line', 'date', 'approval_hour')},
            },
        ),
    ]
