# Generated by Django 5.2.12 on 2026-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0051_qc_hourly_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueUloginRole',
            fields=[
                ('login_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vue_ulogin_role',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='qc_piece_data',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='qc_piece_final',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
