# Generated by Django 5.2.12 on 2026-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0052_vueuloginrole_alter_qc_piece_data_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcHourlyApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('line', models.IntegerField()),
                ('approval_hour', models.IntegerField()),
                ('date', models.DateField()),
                ('unit_incharge_user', models.IntegerField(blank=True, null=True)),
                ('unit_incharge_sign', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', max_length=100, null=True)),
                ('unit_incharge_time', models.DateTimeField(blank=True, null=True)),
                ('oa_user', models.IntegerField(blank=True, null=True)),
                ('oa_sign', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', max_length=100, null=True)),
                ('oa_time', models.DateTimeField(blank=True, null=True)),
                ('fm_user', models.IntegerField(blank=True, null=True)),
                ('fm_sign', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', max_length=100, null=True)),
                ('fm_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'qcapp_qc_hourly_approval',
                'managed': False,
            },
        ),
    ]
