# Generated by Django 5.2.12 on 2026-08-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0053_qchourlyapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_allocate',
            name='jobno',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_allocate',
            name='seq',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='emp_allocate',
            name='top_bottom',
            field=models.CharField(max_length=100),
        ),
    ]
