# Generated by Django 5.2.12 on 2026-08-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0053_qchourlyapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_allocate',
            name='jobno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp_allocate',
            name='seq',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp_allocate',
            name='top_bottom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
