# Generated by Django 5.2.12 on 2026-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0054_alter_emp_allocate_jobno_alter_emp_allocate_seq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementMas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.CharField(max_length=50)),
                ('bundle_no', models.CharField(max_length=50)),
                ('tob_bottom', models.CharField(max_length=50)),
                ('pcs', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'measurement_mas',
            },
        ),
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_id', models.IntegerField()),
                ('mesurement_name', models.CharField(max_length=50)),
                ('d_type', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('tol', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('input_value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'measurement_data',
                'constraints': [models.UniqueConstraint(fields=('mes_id', 'mesurement_name', 'group', 'd_type'), name='unique_measurement_input')],
            },
        ),
    ]
