# Generated by Django 5.2.12 on 2026-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0054_alter_emp_allocate_jobno_alter_emp_allocate_seq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_allocate',
            name='jobno',
            field=models.CharField(max_length=100),
        ),
    ]
