# Generated by Django 5.2.12 on 2026-08-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0055_measurementmas_measurementdata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurementdata',
            name='unique_measurement_input',
        ),
        migrations.AlterModelTable(
            name='measurementdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='measurementmas',
            table=None,
        ),
    ]
