# Generated by Django 5.2.12 on 2026-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0056_remove_measurementdata_unique_measurement_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdata',
            name='jobno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
