# Generated by Django 6.0.7 on 2026-09-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0055_alter_emp_allocate_jobno'),
        ('qcapp', '0057_measurementdata_jobno'),
    ]

    operations = [
    ]
