# Generated by Django 6.0.7 on 2026-09-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0058_merge_20260910_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementData',
        ),
        migrations.DeleteModel(
            name='MeasurementMas',
        ),
    ]
