# Generated by Django 6.0.7 on 2026-09-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0059_delete_measurementdata_delete_measurementmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_id', models.IntegerField()),
                ('mesurement_name', models.CharField(max_length=50)),
                ('d_type', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('tol', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('input_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementMas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.CharField(max_length=50)),
                ('bundle_no', models.CharField(max_length=50)),
                ('tob_bottom', models.CharField(max_length=50)),
                ('pcs', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
