# Generated by Django 6.0.7 on 2026-09-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0060_measurementdata_measurementmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdata',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='qcapp.measurementmas'),
            preserve_default=False,
        ),
    ]
