# Generated by Django 6.0.7 on 2026-09-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0061_measurementdata_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmstAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordno', models.CharField(max_length=50)),
                ('tbid', models.IntegerField()),
                ('measurdtls', models.CharField(max_length=80)),
                ('name', models.CharField(db_column='Name', max_length=35)),
                ('meas', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ty', models.CharField(blank=True, max_length=50, null=True)),
                ('tol', models.CharField(blank=True, max_length=10, null=True)),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
            ],
            options={
                'db_table': 'mmst_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=50)),
                ('top_bottom', models.CharField(max_length=100)),
                ('measurement', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('input_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group', models.CharField(max_length=10)),
                ('d_type', models.CharField(default='STD', max_length=10)),
                ('entry_no', models.CharField(max_length=20)),
                ('jobno', models.CharField(blank=True, default='', max_length=50)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('pcs', models.PositiveIntegerField(blank=True, null=True)),
                ('standard', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tolerance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
