# Generated by Django 6.0.7 on 2026-09-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0062_mmstassign_measuremententry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuremententry',
            name='input_value',
        ),
        migrations.RemoveField(
            model_name='measuremententry',
            name='jobno',
        ),
        migrations.RemoveField(
            model_name='measuremententry',
            name='pcs',
        ),
        migrations.RemoveField(
            model_name='measuremententry',
            name='size',
        ),
        migrations.RemoveField(
            model_name='measuremententry',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='measuremententry',
            name='tolerance',
        ),
    ]
