# Generated by Django 6.0.7 on 2026-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0063_remove_measuremententry_input_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementmas',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
