# Generated by Django 6.0.7 on 2026-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0064_measurementmas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementmas',
            name='plan_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
