# Generated by Django 6.0.7 on 2026-09-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0065_measurementmas_plan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuremententry',
            name='skip_mes',
            field=models.BooleanField(default=False),
        ),
    ]
