# Generated by Django 6.0.7 on 2026-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0066_measuremententry_skip_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuremententry',
            name='mes_order',
            field=models.IntegerField(default=0),
        ),
    ]
