# Generated by Django 6.0.7 on 2026-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0067_measuremententry_mes_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCuttingMeasurmentpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.BigIntegerField(blank=True, null=True)),
                ('planno', models.IntegerField()),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('clrcombo', models.CharField(db_column='Clrcombo', max_length=80)),
                ('lotno', models.CharField(db_column='LotNo', max_length=50)),
                ('name', models.CharField(db_column='Name', max_length=35)),
                ('pc', models.IntegerField(blank=True, null=True)),
                ('markerclassification', models.CharField(blank=True, db_column='MarKerClassification', max_length=50, null=True)),
            ],
            options={
                'db_table': 'view_cutting_measurmentpending',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='measuremententry',
            table='qcapp_measuremententry',
        ),
    ]
