# Generated by Django 6.0.7 on 2026-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0068_viewcuttingmeasurmentpending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPlandetailsWithratio',
            fields=[
                ('rowno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('planno', models.IntegerField(db_column='Planno')),
                ('jobno', models.CharField(db_column='Jobno', max_length=50)),
                ('topbottom', models.CharField(blank=True, max_length=50, null=True)),
                ('ratio', models.CharField(blank=True, max_length=8000, null=True)),
            ],
            options={
                'db_table': 'view_plandetails_withratio',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='measurementmas',
            name='ratio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
