# Generated by Django 6.0.7 on 2026-10-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0069_viewplandetailswithratio_measurementmas_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasContract',
            fields=[
                ('contract_des', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('act', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('cat', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=1550, null=True)),
                ('panno', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PANNo', max_length=25, null=True)),
                ('bill_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Bill_Name', max_length=50, null=True)),
                ('ded', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('ty', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('ph3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('ph2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('ph1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CID', null=True)),
                ('dedper', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Mas_contract',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='cont_employee',
            name='con_id',
            field=models.IntegerField(),
        ),
    ]
