# Generated by Django 6.0.7 on 2026-10-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0071_alter_cont_employee_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cont_employee',
            table='Cont_employee',
        ),
    ]
