# Generated by Django 6.0.7 on 2026-10-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0072_alter_cont_employee_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cont_employee',
            options={},
        ),
    ]
