# Generated by Django 6.0.7 on 2026-10-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0074_alter_cont_employee_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cont_employee',
            table='qcapp_cont_employee',
        ),
    ]
