# Generated by Django 6.0.2 on 2026-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adreq',
            fields=[
                ('entryno', models.IntegerField(db_column='Entryno')),
                ('dt', models.DateTimeField()),
                ('empid', models.IntegerField(db_column='Empid')),
                ('amt', models.DecimalField(db_column='Amt', decimal_places=2, max_digits=18)),
                ('remarks', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=80)),
                ('smon', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2, null=True)),
                ('syear', models.IntegerField(blank=True, null=True)),
                ('elig', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sl', models.AutoField(db_column='SL', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('status_dt', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, null=True)),
                ('mail_sent', models.BooleanField()),
            ],
            options={
                'db_table': 'ladvreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeeworking',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('workunit', models.CharField(blank=True, db_column='WorkUnit', max_length=70, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=70, null=True)),
                ('type', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'EmployeeWorking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empwisesal',
            fields=[
                ('dept', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, db_column='Salary', decimal_places=2, max_digits=18, null=True)),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('wrkunit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('photo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=400, null=True)),
                ('monthlysalary', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MonthlySalary', max_length=1, null=True)),
                ('designation', models.CharField(blank=True, db_column='mcategory', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Empwisesal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncdebUsers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserName', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=50, null=True)),
                ('screen_per', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Screen_per', max_length=50, null=True)),
                ('app_n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IncDeb_Users',
                'managed': False,
            },
        ),
    ]
