# Generated by Django 5.2.12 on 2026-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrWrkdtlsnew',
            fields=[
                ('monthlysalary', models.CharField(blank=True, db_column='MonthlySalary', max_length=1, null=True)),
                ('esino', models.CharField(blank=True, max_length=50, null=True)),
                ('pfno', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=65, null=True)),
                ('status1', models.CharField(blank=True, db_column='Status1', max_length=13, null=True)),
                ('dept_category_unit_pcategory', models.CharField(blank=True, db_column='Dept_Category_Unit_Pcategory', max_length=214, null=True)),
                ('con_sc_astaff', models.CharField(blank=True, max_length=6, null=True)),
                ('picpen', models.CharField(db_column='Picpen', max_length=9)),
                ('tasstaff', models.CharField(blank=True, max_length=3, null=True)),
                ('photo', models.CharField(blank=True, max_length=400, null=True)),
                ('mcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('con_name_mcate', models.CharField(blank=True, db_column='Con_name_mcate', max_length=151, null=True)),
                ('empty', models.CharField(blank=True, db_column='Empty', max_length=50, null=True)),
                ('prab', models.CharField(max_length=7)),
                ('filnam', models.CharField(blank=True, db_column='FILNAM', max_length=44, null=True)),
                ('emppic', models.CharField(blank=True, db_column='Emppic', max_length=8000, null=True)),
                ('prate', models.IntegerField(db_column='Prate')),
                ('trn', models.CharField(db_column='Trn', max_length=1)),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('sc', models.CharField(max_length=2)),
                ('dept', models.CharField(blank=True, max_length=70, null=True)),
                ('prs', models.CharField(blank=True, db_column='PRS', max_length=8000, null=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=70, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('intercom', models.CharField(blank=True, max_length=50, null=True)),
                ('hostel', models.CharField(blank=True, db_column='Hostel', max_length=50, null=True)),
                ('roomdtls', models.CharField(blank=True, db_column='Roomdtls', max_length=50, null=True)),
                ('orissa', models.CharField(blank=True, max_length=3, null=True)),
                ('bank', models.CharField(blank=True, db_column='Bank', max_length=200, null=True)),
                ('accountdetails', models.CharField(blank=True, db_column='Accountdetails', max_length=200, null=True)),
                ('grp2', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, db_column='Qualification', max_length=50, null=True)),
                ('pftype', models.CharField(blank=True, max_length=10, null=True)),
                ('accountdetails1', models.CharField(blank=True, db_column='Accountdetails1', max_length=200, null=True)),
                ('attach', models.CharField(blank=True, max_length=1550, null=True)),
                ('contract_des', models.CharField(max_length=50)),
                ('curwrkunit', models.CharField(blank=True, db_column='CurWrkUnit', max_length=70, null=True)),
                ('inch', models.CharField(max_length=3)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('nattgrp', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.DecimalField(blank=True, db_column='Salary', decimal_places=2, max_digits=18, null=True)),
                ('inspection', models.CharField(blank=True, db_column='INSPECTION', max_length=3, null=True)),
                ('empprs', models.CharField(db_column='Empprs', max_length=80)),
                ('skilled', models.CharField(max_length=10)),
                ('aempwatch', models.CharField(max_length=3)),
                ('joindt', models.DateTimeField(blank=True, db_column='JoinDt', null=True)),
                ('tc', models.CharField(blank=True, max_length=20, null=True)),
                ('createdby', models.DateTimeField(blank=True, null=True)),
                ('modifiedby', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HR_WrkDtlsNew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RptCut002',
            fields=[
                ('sl', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dept', max_length=50, null=True)),
                ('trn', models.IntegerField(blank=True, db_column='Trn', null=True)),
                ('trn1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Trn1', max_length=50, null=True)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('nos', models.IntegerField(blank=True, db_column='Nos', null=True)),
                ('pc', models.IntegerField(blank=True, db_column='Pc', null=True)),
                ('wgt', models.DecimalField(blank=True, db_column='Wgt', decimal_places=3, max_digits=18, null=True)),
                ('mtr', models.DecimalField(blank=True, db_column='Mtr', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Rpt_Cut002',
                'managed': False,
            },
        ),
    ]
