# Generated by Django 5.2.12 on 2026-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0002_hrwrkdtlsnew_rptcut002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthlysaltime',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('modulename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ModuleName', max_length=50)),
                ('dayofweek', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DayOfWeek', max_length=15)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('starttime', models.TimeField(db_column='StartTime')),
                ('endtime', models.TimeField(db_column='EndTime')),
                ('updatedat', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
            ],
            options={
                'db_table': 'Monthlysaltime',
                'managed': False,
            },
        ),
    ]
