# Generated by Django 5.2.12 on 2026-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0003_monthlysaltime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncdebUsers',
        ),
    ]
