# Generated by Django 6.0.7 on 2026-09-14 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_vuerepcutpend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Replace_Cutpend',
            fields=[
                ('slno', models.AutoField(db_column='SlNo', primary_key=True, serialize=False)),
                ('styleid', models.IntegerField(db_column='StyleID')),
                ('size', models.CharField(blank=True, db_column='Size', max_length=20, null=True)),
                ('topbottom', models.CharField(blank=True, db_column='TopBottom', max_length=50, null=True)),
                ('parts', models.CharField(blank=True, db_column='Parts', max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=2, max_digits=10, null=True)),
                ('average', models.DecimalField(blank=True, db_column='Average', decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, db_column='Percentage', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Master_Repcutpend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repcutpending',
            fields=[
                ('slno', models.AutoField(db_column='SlNo', primary_key=True, serialize=False)),
                ('jobno', models.CharField(db_column='JobNo', max_length=20)),
                ('size', models.CharField(db_column='Size', max_length=20)),
                ('topbottom', models.CharField(blank=True, db_column='TopBottom', max_length=50, null=True)),
                ('parts', models.CharField(blank=True, db_column='Parts', max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=2, max_digits=10, null=True)),
                ('average', models.DecimalField(blank=True, db_column='Average', decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, db_column='Percentage', decimal_places=2, max_digits=10, null=True)),
                ('datetym', models.DateTimeField(db_column='Datetym', default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'RepcutPending',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View_Master_RepcutPend',
            fields=[
                ('siz', models.CharField(db_column='Siz', max_length=50, primary_key=True, serialize=False)),
                ('det_main_part', models.CharField(blank=True, max_length=50, null=True)),
                ('det_part', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'view_mrep_cut_pend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewRepcutPend',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('jobno', models.CharField(blank=True, max_length=50, null=True)),
                ('siz', models.CharField(blank=True, db_column='Siz', max_length=50, null=True)),
                ('det_main_part', models.CharField(blank=True, max_length=50, null=True)),
                ('det_part', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'view_repcut_pend',
                'managed': False,
            },
        ),
    ]
