# Generated by Django 6.0.7 on 2026-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_trshrrsgndtls_txorderdetstyles_vuedyeingratenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueRepCutPend',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('jobno', models.CharField(max_length=50)),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('clrcombo', models.CharField(max_length=50)),
                ('siz', models.CharField(max_length=35)),
                ('lotno', models.CharField(max_length=50)),
                ('panel_description', models.CharField(blank=True, max_length=8000, null=True)),
                ('mistake_pcs', models.IntegerField(blank=True, db_column='Mistake_Pcs', null=True)),
                ('mistake_panel_count', models.IntegerField(blank=True, db_column='Mistake_Panel_Count', null=True)),
                ('merge_pcs', models.IntegerField(db_column='Merge_Pcs')),
                ('replace_cutting_pcs', models.IntegerField(db_column='Replace_Cutting_Pcs')),
                ('status', models.CharField(db_column='Status', max_length=7)),
                ('pendpc', models.IntegerField()),
            ],
            options={
                'db_table': 'vue_rep_cut_pend',
                'managed': False,
            },
        ),
    ]
