# Generated by Django 6.0.7 on 2026-10-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_master_replace_cutpend_repcutpending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrsOverAllemb',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(db_column='Dt')),
                ('dept', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dept', max_length=50)),
                ('code', models.IntegerField()),
            ],
            options={
                'db_table': 'Trs_Over_AllEmb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewAbsentList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unitname', models.CharField(max_length=50)),
                ('month', models.CharField(blank=True, db_column='m', max_length=3, null=True)),
                ('year', models.IntegerField(blank=True, db_column='y', null=True)),
                ('workingdays', models.IntegerField(blank=True, db_column='days', null=True)),
                ('leave_days', models.IntegerField(blank=True, db_column='leavdays', null=True)),
                ('informed', models.IntegerField(blank=True, db_column='inl', null=True)),
                ('shiftdays', models.IntegerField(blank=True, db_column='actshiftdays', null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.CharField(blank=True, max_length=443, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('stat', models.IntegerField(db_column='Stat')),
                ('mon_order', models.IntegerField()),
            ],
            options={
                'db_table': 'view_absent_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewEmployeeAtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('ashift', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('aot', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('a', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'view_employee_att',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewEmployeeSalaryDetails',
            fields=[
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('esino', models.CharField(blank=True, max_length=50, null=True)),
                ('pfno', models.CharField(blank=True, max_length=100, null=True)),
                ('uanno', models.CharField(blank=True, max_length=50, null=True)),
                ('doj', models.DateTimeField(blank=True, null=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fname', models.CharField(db_column='Fname', max_length=1)),
                ('sex', models.CharField(max_length=6)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('mon', models.IntegerField(blank=True, db_column='MON', null=True)),
                ('yr', models.IntegerField(blank=True, null=True)),
                ('monthname', models.CharField(blank=True, max_length=30, null=True)),
                ('day', models.DecimalField(blank=True, db_column='DAY', decimal_places=2, max_digits=38, null=True)),
                ('ot', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('salary1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('paidholiday', models.IntegerField()),
                ('onehr_wag', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('double_wag', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('ot_amt', models.DecimalField(blank=True, decimal_places=6, max_digits=38, null=True)),
                ('sum_ofwage', models.DecimalField(blank=True, decimal_places=4, max_digits=38, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=6, max_digits=38, null=True)),
                ('earned', models.DecimalField(blank=True, decimal_places=4, max_digits=38, null=True)),
                ('esi', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ('pf', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ('netamt', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'view_employee_salary_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewStaffAbsentMonth',
            fields=[
                ('rn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('yr', models.IntegerField(blank=True, null=True)),
                ('mn', models.IntegerField(blank=True, null=True)),
                ('monthname', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('absentdays', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=70)),
                ('wunit', models.CharField(blank=True, max_length=70, null=True)),
                ('cat', models.CharField(blank=True, max_length=70, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'view_staff_absent_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewStaffLateMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.BigIntegerField(blank=True, null=True)),
                ('yr', models.IntegerField(blank=True, db_column='Yr', null=True)),
                ('mn', models.IntegerField(blank=True, db_column='Mn', null=True)),
                ('monthname', models.CharField(blank=True, db_column='MonthName', max_length=30, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('wunit', models.CharField(blank=True, max_length=70, null=True)),
                ('cat', models.CharField(blank=True, max_length=70, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('latedays', models.IntegerField(blank=True, db_column='LateDays', null=True)),
                ('latemins', models.IntegerField(blank=True, db_column='LateMins', null=True)),
            ],
            options={
                'db_table': 'view_staff_late_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueOtAmountStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wunit', models.CharField(blank=True, max_length=70, null=True)),
                ('cat', models.CharField(blank=True, db_column='ACAT', max_length=70, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('otamt', models.DecimalField(blank=True, decimal_places=6, max_digits=38, null=True)),
                ('otmins', models.DecimalField(blank=True, db_column='OTmins', decimal_places=2, max_digits=38, null=True)),
                ('name', models.CharField(max_length=70)),
                ('monthname', models.CharField(blank=True, db_column='Month_Name', max_length=3, null=True)),
                ('mn', models.IntegerField(blank=True, db_column='MonthNo', null=True)),
                ('yr', models.IntegerField(blank=True, db_column='YR', null=True)),
                ('code', models.IntegerField(db_column='EmpID')),
            ],
            options={
                'db_table': 'vue_ot_amount_staff',
                'managed': False,
            },
        ),
    ]
