# Generated by Django 6.0.7 on 2026-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_trsoverallemb_viewabsentlist_viewemployeeatt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewActshift',
            fields=[
                ('rowno', models.BigIntegerField(db_column='RowNo', primary_key=True, serialize=False)),
                ('unitname', models.CharField(db_column='Unitname', max_length=50)),
                ('id', models.IntegerField()),
                ('actshift', models.DecimalField(blank=True, db_column='Actshift', decimal_places=2, max_digits=38, null=True)),
                ('code', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('mno', models.IntegerField(blank=True, null=True)),
                ('yr', models.IntegerField(blank=True, null=True)),
                ('monthname', models.CharField(blank=True, db_column='MonthName', max_length=30, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
            ],
            options={
                'db_table': 'view_actshift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewActshiftDay',
            fields=[
                ('rowno', models.BigIntegerField(db_column='RowNo', primary_key=True, serialize=False)),
                ('unitname', models.CharField(db_column='Unitname', max_length=50)),
                ('id', models.IntegerField()),
                ('dt', models.DateTimeField()),
                ('actshift', models.DecimalField(db_column='Actshift', decimal_places=2, max_digits=18)),
                ('code', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
            ],
            options={
                'db_table': 'view_actshift_day',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BillAge',
        ),
        migrations.DeleteModel(
            name='BillMdapprove',
        ),
        migrations.DeleteModel(
            name='BillPass',
        ),
        migrations.DeleteModel(
            name='Holdwagepaid',
        ),
        migrations.DeleteModel(
            name='VueHoldwage',
        ),
    ]
