# Generated by Django 5.2.12 on 2026-08-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('module_id', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_module_permissions',
                'unique_together': {('role', 'module_id')},
            },
        ),
    ]
