# Generated by Django 6.0.7 on 2026-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCutsecFabricdelivery',
            fields=[
                ('rlno', models.CharField(db_column='RlNo', max_length=50, primary_key=True, serialize=False)),
                ('dcaddres', models.CharField(blank=True, max_length=750, null=True)),
                ('delto', models.CharField(blank=True, max_length=750, null=True)),
                ('dt', models.DateTimeField(db_column='Dt')),
                ('dcno', models.IntegerField()),
                ('purpose_name', models.CharField(db_column='Purpose_Name', max_length=80)),
                ('jobno', models.CharField(blank=True, max_length=50, null=True)),
                ('clr', models.CharField(blank=True, max_length=50, null=True)),
                ('fab', models.CharField(max_length=35)),
                ('lotno', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(db_column='Name', max_length=35)),
                ('wgtkgs', models.DecimalField(db_column='WgtKgs', decimal_places=3, max_digits=18)),
                ('mtr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'view_cutsec_fabricdelivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dc_Incharge_Verify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('DCNo', models.IntegerField(db_column='DCNo')),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('trstype', models.CharField(db_column='TrsType', max_length=50)),
                ('wgt', models.DecimalField(blank=True, db_column='Wgt', decimal_places=3, max_digits=18, null=True)),
                ('mtr', models.DecimalField(blank=True, db_column='Mtr', decimal_places=2, max_digits=18, null=True)),
                ('rolls', models.IntegerField(blank=True, db_column='Rolls', null=True)),
                ('bags', models.CharField(blank=True, db_column='Bags', max_length=50, null=True)),
                ('username', models.IntegerField(db_column='Username')),
            ],
            options={
                'db_table': 'dc_incharge_verify',
            },
        ),
        migrations.CreateModel(
            name='Dc_Reciver_Verify',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('DCNo', models.IntegerField(db_column='DCNo')),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('trstype', models.CharField(db_column='TrsType', max_length=50)),
                ('wgt', models.DecimalField(blank=True, db_column='Wgt', decimal_places=3, max_digits=18, null=True)),
                ('mtr', models.DecimalField(blank=True, db_column='Mtr', decimal_places=2, max_digits=18, null=True)),
                ('rolls', models.IntegerField(blank=True, db_column='Rolls', null=True)),
                ('bags', models.CharField(blank=True, db_column='Bags', max_length=50, null=True)),
                ('username', models.IntegerField(db_column='Username')),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=7, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=500, null=True)),
                ('receiver_image', models.ImageField(blank=True, db_column='ReceiverImage', null=True, upload_to='dc_receiver/')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_column='ReceivedAt')),
            ],
            options={
                'db_table': 'dc_receiver_verify',
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('module_id', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_module_permissions',
                'unique_together': {('role', 'module_id')},
            },
        ),
    ]
