# Generated by Django 6.0.7 on 2026-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_reciver_verify',
            name='concat_location',
            field=models.CharField(blank=True, db_column='Concate_Location', max_length=100, null=True),
        ),
    ]
