# Generated by Django 6.0.7 on 2026-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0002_dc_reciver_verify_concat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_reciver_verify',
            name='jobno',
            field=models.CharField(blank=True, db_column='JobNo', max_length=50, null=True),
        ),
    ]
