# Generated by Django 6.0.7 on 2026-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0002_rolemodulepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCutsecFabricdelivery',
            fields=[
                ('rlno', models.CharField(db_column='RlNo', max_length=50, primary_key=True, serialize=False)),
                ('dcaddres', models.CharField(blank=True, max_length=750, null=True)),
                ('delto', models.CharField(blank=True, max_length=750, null=True)),
                ('dt', models.DateTimeField(db_column='Dt')),
                ('dcno', models.IntegerField()),
                ('purpose_name', models.CharField(db_column='Purpose_Name', max_length=80)),
                ('jobno', models.CharField(blank=True, max_length=50, null=True)),
                ('clr', models.CharField(blank=True, max_length=50, null=True)),
                ('fab', models.CharField(max_length=35)),
                ('lotno', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(db_column='Name', max_length=35)),
                ('wgtkgs', models.DecimalField(db_column='WgtKgs', decimal_places=3, max_digits=18)),
                ('mtr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'view_cutsec_fabricdelivery',
                'managed': False,
            },
        ),
    ]
