# Generated by Django 6.0.7 on 2026-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0003_alter_dc_reciver_verify_jobno'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_incharge_verify',
            name='status',
            field=models.BooleanField(db_column='Status', default=False),
        ),
    ]
