# Generated by Django 6.0.7 on 2026-09-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0003_viewcutsecfabricdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dc_Verify_Incharge',
            fields=[
                ('slno', models.BigIntegerField(db_column='SlNo', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('DCNo', models.IntegerField(db_column='DCNo')),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('trstype', models.CharField(db_column='TrsType', max_length=50)),
                ('wgt', models.DecimalField(blank=True, db_column='Wgt', decimal_places=3, max_digits=18, null=True)),
                ('mtr', models.DecimalField(blank=True, db_column='Mtr', decimal_places=2, max_digits=18, null=True)),
                ('rolls', models.IntegerField(blank=True, db_column='Rolls', null=True)),
                ('bags', models.CharField(blank=True, db_column='Bags', max_length=50, null=True)),
                ('username', models.IntegerField(db_column='Username')),
            ],
            options={
                'db_table': 'dc_verify_incharge',
                'managed': False,
            },
        ),
    ]
