# Generated by Django 6.0.7 on 2026-09-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0004_dc_verify_incharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dc_verify_incharge',
            options={},
        ),
    ]
