# Generated by Django 6.0.7 on 2026-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0004_dc_incharge_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_reciver_verify',
            name='qty',
            field=models.BigIntegerField(blank=True, db_column='Qty', max_length=10, null=True),
        ),
    ]
