# Generated by Django 6.0.7 on 2026-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0005_dc_reciver_verify_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_reciver_verify',
            name='qty',
            field=models.DecimalField(blank=True, db_column='Qty', decimal_places=2, max_digits=10, null=True),
        ),
    ]
