# Generated by Django 6.0.7 on 2026-10-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0006_alter_dc_reciver_verify_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_reciver_verify',
            name='status',
            field=models.BooleanField(db_column='Status', default=False),
        ),
    ]
