# Generated by Django 6.0.7 on 2026-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0006_create_dc_verify_incharge_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dc_Reciver_Incharge',
            fields=[
                ('id', models.AutoField(db_column='SlNo', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('DCNo', models.IntegerField(db_column='DCNo')),
                ('jobno', models.CharField(db_column='JobNo', max_length=50)),
                ('trstype', models.CharField(db_column='TrsType', max_length=50)),
                ('wgt', models.DecimalField(blank=True, db_column='Wgt', decimal_places=3, max_digits=18, null=True)),
                ('mtr', models.DecimalField(blank=True, db_column='Mtr', decimal_places=2, max_digits=18, null=True)),
                ('rolls', models.IntegerField(blank=True, db_column='Rolls', null=True)),
                ('bags', models.CharField(blank=True, db_column='Bags', max_length=50, null=True)),
                ('username', models.IntegerField(db_column='Username')),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=7, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=500, null=True)),
                ('receiver_image', models.ImageField(blank=True, db_column='ReceiverImage', null=True, upload_to='dc_receiver/')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_column='ReceivedAt')),
            ],
            options={
                'db_table': 'dc_receiver_incharge',
            },
        ),
        migrations.RemoveField(
            model_name='dc_verify_incharge',
            name='slno',
        ),
        migrations.AddField(
            model_name='dc_verify_incharge',
            name='id',
            field=models.AutoField(db_column='SlNo', primary_key=True, serialize=False),
        ),
    ]
