# Generated by Django 6.0.7 on 2026-10-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0002_viewcutsecfabricdelivery_dc_incharge_verify_and_more'),
        ('dc_app', '0007_dc_reciver_verify_status'),
    ]

    operations = [
    ]
