# Generated by Django 6.0.7 on 2026-09-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0007_dc_reciver_incharge_remove_dc_verify_incharge_slno_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dc_Reciver_Incharge',
            new_name='Dc_Reciver_Verify',
        ),
    ]
