# Generated by Django 6.0.7 on 2026-10-06 09:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0008_merge_20261006_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewGeneralDeiveryType1',
            fields=[
                ('phone1', models.CharField(blank=True, db_column='Phone1', max_length=50, null=True)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, max_length=12, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=50, null=True)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=50, null=True)),
                ('address3', models.CharField(blank=True, db_column='Address3', max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=66, null=True)),
                ('regno', models.CharField(blank=True, db_column='RegNo', max_length=20, null=True)),
                ('s', models.CharField(blank=True, max_length=34, null=True)),
                ('suppliername', models.CharField(blank=True, max_length=35, null=True)),
                ('sadd1', models.CharField(blank=True, max_length=50, null=True)),
                ('sadd2', models.CharField(blank=True, max_length=50, null=True)),
                ('sadd3', models.CharField(blank=True, max_length=50, null=True)),
                ('cityname', models.CharField(blank=True, max_length=35, null=True)),
                ('statname', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=2, null=True)),
                ('no', models.IntegerField(db_column='No')),
                ('date', models.DateTimeField(db_column='Date')),
                ('reference', models.CharField(blank=True, db_column='Reference', max_length=20, null=True)),
                ('incharge', models.CharField(blank=True, max_length=35, null=True)),
                ('item', models.CharField(blank=True, db_column='Item', max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='Quantity', decimal_places=4, max_digits=18, null=True)),
                ('uomname', models.CharField(blank=True, max_length=25, null=True)),
                ('duedate', models.DateTimeField(blank=True, db_column='DueDate', null=True)),
                ('ty', models.CharField(max_length=10)),
                ('dd1', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=50, null=True)),
                ('qrid', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'view_general_deivery_type1',
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            # These database changes were already applied by migrations 0002-0007.
            # The merge migration's state follows the other 0002 branch, so only
            # synchronize Django's state here and do not add the columns again.
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='dc_incharge_verify',
                    name='status',
                    field=models.BooleanField(db_column='Status', default=False),
                ),
                migrations.AddField(
                    model_name='dc_reciver_verify',
                    name='concat_location',
                    field=models.CharField(blank=True, db_column='Concate_Location', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='dc_reciver_verify',
                    name='qty',
                    field=models.DecimalField(blank=True, db_column='Qty', decimal_places=2, max_digits=10, null=True),
                ),
                migrations.AddField(
                    model_name='dc_reciver_verify',
                    name='status',
                    field=models.BooleanField(db_column='Status', default=False),
                ),
                migrations.AlterField(
                    model_name='dc_reciver_verify',
                    name='jobno',
                    field=models.CharField(blank=True, db_column='JobNo', max_length=50, null=True),
                ),
                migrations.AlterField(
                    model_name='dc_reciver_verify',
                    name='receiver_image',
                    field=models.ImageField(blank=True, db_column='ReceiverImage', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/dc_receiver_images_network/', location='\\\\10.1.21.11\\d\\DC_Reciver_image'), upload_to=''),
                ),
            ],
        ),
    ]
