# Generated by Django 6.0.7 on 2026-09-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0008_rename_dc_reciver_incharge_dc_reciver_verify'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dc_reciver_verify',
            table='dc_receiver_verify',
        ),
    ]
