# Generated by Django 6.0.7 on 2026-10-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0008_merge_20261006_1727'),
        ('dc_app', '0009_viewgeneraldeiverytype1_dc_incharge_verify_status_and_more'),
    ]

    operations = [
    ]
