# Generated by Django 6.0.7 on 2026-09-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_app', '0010_alter_dc_reciver_verify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_verify_incharge',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
