# Generated by Django 5.2.12 on 2026-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmpPrdprn',
            fields=[
                ('ip', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, primary_key=True, serialize=False)),
                ('unit', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Unit', max_length=50)),
                ('jobno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Jobno', max_length=50)),
                ('tb', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tb', max_length=50)),
                ('clr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('bc', models.IntegerField()),
                ('sew', models.IntegerField()),
                ('che', models.IntegerField()),
                ('irn', models.IntegerField()),
                ('pack', models.IntegerField()),
                ('oth', models.IntegerField()),
                ('mist', models.IntegerField()),
                ('trstype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=80, null=True)),
                ('ordqty', models.IntegerField(blank=True, null=True)),
                ('fc', models.IntegerField(blank=True, null=True)),
                ('allotqty', models.IntegerField(blank=True, null=True)),
                ('cutqtyqty', models.IntegerField(blank=True, null=True)),
                ('rejqty', models.IntegerField(blank=True, null=True)),
                ('singer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_tmp_prdprn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TxNotification',
            fields=[
                ('emp_code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('wunit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('cat', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('punch_time', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('dt', models.DateField(blank=True, null=True)),
                ('sl', models.AutoField(primary_key=True, serialize=False)),
                ('processed', models.BooleanField(blank=True, null=True)),
                ('pic', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('late', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'tx_notification',
                'managed': False,
            },
        ),
    ]
