# Generated by Django 6.0.7 on 2026-09-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_category_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operation_Category_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=20)),
                ('operations', models.CharField(max_length=100)),
                ('machine_cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salary_Confirmation.machine_category_master')),
            ],
        ),
    ]
