# Generated by Django 6.0.7 on 2026-09-29 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary_Confirmation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_category_master',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine_category_master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operation_category_master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation_category_master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
