# Generated by Django 6.0.7 on 2026-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary_Confirmation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Operation_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=20)),
                ('machine_name', models.CharField(max_length=50)),
                ('operations', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Master_Operation_Category',
            },
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='operation_category_master',
                    name='machine_cate_id',
                ),
                migrations.DeleteModel(
                    name='Machine_category_master',
                ),
                migrations.DeleteModel(
                    name='Operation_Category_master',
                ),
            ],
        ),
    ]