# Generated by Django 6.0.7 on 2026-10-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary_Confirmation', '0002_master_operation_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasProcess',
            fields=[
                ('process_id', models.IntegerField(db_column='Process_ID', primary_key=True, serialize=False)),
                ('process_des', models.CharField(blank=True, db_column='Process_des', max_length=150, null=True)),
                ('mc', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Mas_Process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salcon_Approval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('salary_approved', models.IntegerField()),
                ('approve_fm', models.IntegerField()),
                ('approve_fm_date', models.DateTimeField()),
                ('approve_hr', models.IntegerField()),
                ('approve_hr_date', models.DateTimeField()),
                ('approve_md', models.IntegerField()),
                ('approve_md_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salcon_Employee_Details',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('prev_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prev_company', models.CharField(max_length=50)),
                ('prev_category', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('current_category', models.CharField(max_length=50)),
                ('current_grade', models.CharField(max_length=50)),
                ('evaluation_date', models.DateField()),
                ('unit', models.CharField(max_length=30)),
                ('salary_recommendation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salcon_Individual_Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('assessment_criteria', models.CharField(max_length=100)),
                ('assessment_status', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('prepared_ie', models.CharField(max_length=50)),
                ('approved_pi', models.CharField(max_length=50)),
                ('slno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salary_Confirmation.salcon_employee_details')),
            ],
        ),
        migrations.CreateModel(
            name='Salcon_Operation_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_id', models.IntegerField()),
                ('jobno', models.CharField(max_length=20)),
                ('topbottom', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField()),
                ('oper_category', models.CharField(max_length=20)),
                ('sam_time', models.TimeField()),
                ('cycle_time1', models.TimeField()),
                ('cycle_time2', models.TimeField()),
                ('cycle_time3', models.TimeField()),
                ('cycle_time4', models.TimeField()),
                ('cycle_time5', models.TimeField()),
                ('avg_with_alw', models.TimeField()),
                ('given', models.IntegerField()),
                ('achved', models.IntegerField()),
                ('efficiency', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salary_Confirmation.salcon_employee_details')),
            ],
        ),
        migrations.DeleteModel(
            name='Master_Operation_Category',
        ),
        migrations.AddField(
            model_name='salcon_approval',
            name='slno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salary_Confirmation.salcon_employee_details'),
        ),
    ]
