# Generated by Django 5.2.12 on 2026-08-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionrResult',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('result', models.JSONField(default=list)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('jobno', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Fashionr_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrCutplanMas',
            fields=[
                ('cutplanid', models.AutoField(db_column='CutPlanId', primary_key=True, serialize=False)),
                ('orderno', models.CharField(blank=True, db_column='OrderNo', max_length=50, null=True)),
                ('customer', models.CharField(blank=True, db_column='Customer', max_length=100, null=True)),
                ('fabrictype', models.CharField(blank=True, db_column='FabricType', max_length=100, null=True)),
                ('projectname', models.CharField(blank=True, db_column='ProjectName', max_length=50, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
                ('classification', models.CharField(blank=True, db_column='Classification', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Fr_Cutplan_Mas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrCutplanTotalmarkerlistdet',
            fields=[
                ('markerid', models.AutoField(db_column='MarkerId', primary_key=True, serialize=False)),
                ('entry', models.CharField(blank=True, db_column='Entry', max_length=100, null=True)),
                ('colorway', models.CharField(blank=True, db_column='Colorway', max_length=100, null=True)),
                ('sizesonmarker', models.CharField(blank=True, db_column='SizesOnMarker', max_length=100, null=True)),
                ('noofpiece', models.IntegerField(blank=True, db_column='NoOfPiece', null=True)),
                ('numberofplys', models.IntegerField(blank=True, db_column='NumberOfPlys', null=True)),
                ('edgetoedgeincm', models.DecimalField(blank=True, db_column='EdgeToEdgeInCM', decimal_places=3, max_digits=18, null=True)),
                ('cuttablewidthincm', models.DecimalField(blank=True, db_column='CuttableWidthInCM', decimal_places=3, max_digits=18, null=True)),
                ('length', models.DecimalField(blank=True, db_column='Length', decimal_places=3, max_digits=18, null=True)),
                ('cuttingperimeter', models.DecimalField(blank=True, db_column='CuttingPerimeter', decimal_places=3, max_digits=18, null=True)),
                ('efficiencywithoutselvage', models.DecimalField(blank=True, db_column='EfficiencyWithoutSelvage', decimal_places=3, max_digits=18, null=True)),
                ('efficiencywithselvage', models.DecimalField(blank=True, db_column='EfficiencyWithSelvage', decimal_places=3, max_digits=18, null=True)),
                ('totalpieces', models.IntegerField(blank=True, db_column='TotalPieces', null=True)),
                ('splicemarker', models.TextField(blank=True, db_column='SpliceMarker', null=True)),
                ('cutpercentage', models.DecimalField(blank=True, db_column='CutPercentage', decimal_places=3, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'FR_CutPlan_TotalMarkerListDet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrCutplanSizeandQuantityList',
            fields=[
                ('cutplanid', models.ForeignKey(db_column='CutPlanId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fashionr.frcutplanmas')),
                ('sizename', models.CharField(blank=True, db_column='SizeName', max_length=50, null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
            ],
            options={
                'db_table': 'FR_CutPlan_SizeAndQuantityList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrCutplanTotalMarkerList',
            fields=[
                ('cutplanid', models.ForeignKey(db_column='CutPlanId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fashionr.frcutplanmas')),
                ('orderinformationfabric', models.CharField(blank=True, db_column='OrderInformationFabric', max_length=100, null=True)),
                ('fabricname', models.CharField(blank=True, db_column='FabricName', max_length=100, null=True)),
                ('gsm', models.IntegerField(blank=True, db_column='Gsm', null=True)),
                ('totalnumberofplys', models.IntegerField(blank=True, db_column='TotalNumberOfPlys', null=True)),
                ('totalnumberofpieces', models.IntegerField(blank=True, db_column='TotalNumberOfPieces', null=True)),
                ('totalcuttingperimeter', models.DecimalField(blank=True, db_column='TotalCuttingPerimeter', decimal_places=3, max_digits=18, null=True)),
                ('averageefficiencywithselvage', models.DecimalField(blank=True, db_column='AverageEfficiencyWithSelvage', decimal_places=3, max_digits=18, null=True)),
                ('averageefficiencywithoutselvage', models.DecimalField(blank=True, db_column='AverageEfficiencyWithoutSelvage', decimal_places=3, max_digits=18, null=True)),
                ('numberofmarkers', models.IntegerField(blank=True, db_column='NumberOfMarkers', null=True)),
                ('gap', models.DecimalField(blank=True, db_column='Gap', decimal_places=3, max_digits=18, null=True)),
                ('numberofpanel', models.IntegerField(blank=True, db_column='NumberOfPanel', null=True)),
                ('recommendedspreadinglength', models.IntegerField(blank=True, db_column='RecommendedSpreadingLength', null=True)),
                ('spreadingoption', models.CharField(blank=True, db_column='SpreadingOption', max_length=50, null=True)),
                ('avgproductwtingm', models.DecimalField(blank=True, db_column='AvgProductWtInGm', decimal_places=3, max_digits=18, null=True)),
                ('avgfabricwtconsumptioningm', models.DecimalField(blank=True, db_column='AvgFabricWtConsumptionInGm', decimal_places=3, max_digits=18, null=True)),
                ('avgfabricconsumptioninmetre', models.DecimalField(blank=True, db_column='AvgFabricConsumptionInMetre', decimal_places=3, max_digits=18, null=True)),
                ('totalfabricconsumptioninmetre', models.DecimalField(blank=True, db_column='TotalFabricConsumptionInMetre', decimal_places=3, max_digits=18, null=True)),
                ('totalfabricconsumptioningm', models.DecimalField(blank=True, db_column='TotalFabricConsumptionInGm', decimal_places=3, max_digits=18, null=True)),
                ('selvagewidthincm', models.DecimalField(blank=True, db_column='SelvageWidthInCM', decimal_places=3, max_digits=18, null=True)),
                ('selvagelengthincm', models.DecimalField(blank=True, db_column='SelvageLengthInCM', decimal_places=3, max_digits=18, null=True)),
                ('totalfabricconsumptioninkg', models.DecimalField(blank=True, db_column='TotalFabricConsumptionInKg', decimal_places=3, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'FR_CutPlan_TotalMarkerList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrCutplanTotalmarkerlistimages',
            fields=[
                ('cutplanid', models.ForeignKey(db_column='CutPlanId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fashionr.frcutplanmas')),
                ('markerimage', models.TextField(blank=True, db_column='MarkerImage', null=True)),
                ('fabricwidth', models.DecimalField(blank=True, db_column='FabricWidth', decimal_places=3, max_digits=18, null=True)),
                ('cuttablewidth', models.DecimalField(blank=True, db_column='CuttableWidth', decimal_places=3, max_digits=18, null=True)),
                ('laylength', models.DecimalField(blank=True, db_column='LayLength', decimal_places=3, max_digits=18, null=True)),
                ('averageconsumption', models.DecimalField(blank=True, db_column='AverageConsumption', decimal_places=9, max_digits=18, null=True)),
                ('numberofpieces', models.IntegerField(blank=True, db_column='NumberOfPieces', null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
                ('placed', models.IntegerField(blank=True, db_column='Placed', null=True)),
                ('averagearea', models.DecimalField(blank=True, db_column='AverageArea', decimal_places=3, max_digits=18, null=True)),
                ('fabricarea', models.DecimalField(blank=True, db_column='FabricArea', decimal_places=3, max_digits=18, null=True)),
                ('patternarea', models.DecimalField(blank=True, db_column='PatternArea', decimal_places=3, max_digits=18, null=True)),
                ('wastage', models.DecimalField(blank=True, db_column='Wastage', decimal_places=3, max_digits=18, null=True)),
                ('warpshrinkage', models.IntegerField(blank=True, db_column='WarpShrinkage', null=True)),
                ('weftshrinkage', models.IntegerField(blank=True, db_column='WeftShrinkage', null=True)),
                ('avgwt', models.DecimalField(blank=True, db_column='AvgWt', decimal_places=3, max_digits=18, null=True)),
                ('selvagelengthincm', models.DecimalField(blank=True, db_column='SelvageLengthInCM', decimal_places=3, max_digits=18, null=True)),
                ('totalweightofmarkers', models.DecimalField(blank=True, db_column='TotalWeightOfMarkers', decimal_places=3, max_digits=18, null=True)),
                ('patternweight', models.DecimalField(blank=True, db_column='PatternWeight', decimal_places=3, max_digits=18, null=True)),
                ('wastageweight', models.DecimalField(blank=True, db_column='WastageWeight', decimal_places=3, max_digits=18, null=True)),
                ('gsm', models.IntegerField(blank=True, db_column='GSM', null=True)),
                ('style', models.CharField(blank=True, db_column='Style', max_length=50, null=True)),
            ],
            options={
                'db_table': 'FR_CutPlan_TotalMarkerListImages',
                'managed': False,
            },
        ),
    ]
