# Generated by Django 5.2.12 on 2026-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unit_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.CharField(max_length=50)),
                ('mbud', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
                ('line', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('job_no', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('scan', models.BooleanField(default=False)),
                ('size', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
