# Generated by Django 5.2.12 on 2026-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msizes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=35, unique=True)),
                ('sizegroup', models.IntegerField(blank=True, db_column='SizeGroup', null=True)),
                ('sorter', models.IntegerField(db_column='Sorter')),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'mSizes',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='unit_input',
            name='bdl_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_input',
            name='lot',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_input',
            name='pc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_input',
            name='size_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_input',
            name='tb_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit_input',
            name='tb_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
