# Generated by Django 5.2.12 on 2026-07-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0002_msizes_unit_input_bdl_no_unit_input_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_input',
            name='entry_date',
            field=models.DateTimeField(),
        ),
    ]
