# Generated by Django 5.2.12 on 2026-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0003_alter_unit_input_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('line', models.IntegerField()),
                ('job_no', models.CharField(max_length=50)),
                ('tb_id', models.IntegerField()),
                ('tb_name', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('bundle_id', models.CharField(max_length=50)),
                ('bdl_no', models.CharField(max_length=50)),
                ('mbud', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('size_id', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('pc', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField()),
                ('scan', models.BooleanField(default=False)),
                ('lot', models.CharField(max_length=50)),
            ],
        ),
    ]
