# Generated by Django 5.2.12 on 2026-07-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0004_assembly_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_no', models.CharField(max_length=50)),
                ('tb_id', models.IntegerField()),
                ('tb_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('process_des', models.CharField(max_length=50)),
                ('mc', models.CharField(max_length=50)),
                ('thrd', models.IntegerField()),
                ('wsec', models.CharField(max_length=50)),
                ('process_id', models.IntegerField()),
                ('and_or', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='dependency_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('descriptions', models.CharField(max_length=50)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='production_live_scan.dependency')),
            ],
        ),
    ]
