# Generated by Django 5.2.12 on 2026-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0005_dependency_dependency_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependency_data',
            name='tb_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
