# Generated by Django 5.2.12 on 2026-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0006_dependency_verify_dependency_data_tb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency_data',
            name='desc_ord_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
