# Generated by Django 5.2.12 on 2026-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0007_dependency_data_desc_ord_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency_data',
            name='process_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
