# Generated by Django 5.2.12 on 2026-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0008_dependency_data_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_data',
            name='seq',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
