# Generated by Django 5.2.12 on 2026-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0009_assembly_data_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='assemply_scan',
            field=models.BooleanField(default=False),
        ),
    ]
