# Generated by Django 5.2.12 on 2026-07-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0010_dependency_assemply_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='assemply_scan',
        ),
        migrations.AddField(
            model_name='assembly_data',
            name='process_des',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
