# Generated by Django 5.2.12 on 2026-07-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0011_remove_dependency_assemply_scan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly_data',
            name='process_des',
        ),
    ]
