# Generated by Django 5.2.12 on 2026-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0013_end_line_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_data',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
