# Generated by Django 6.0.7 on 2026-09-12 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0014_assembly_data_emp_id'),
        ('qcapp', '0058_merge_20260910_1820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_unit_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('qcapp', 'QC App'), ('live_app', 'Live App')], max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_unit_permission',
                'constraints': [models.UniqueConstraint(fields=('user', 'app', 'unit'), name='unique_user_app_unit')],
            },
        ),
    ]
