# Generated by Django 6.0.7 on 2026-10-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0016_dependency_or_only_dependency_data_and_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='or_only',
        ),
        migrations.RemoveField(
            model_name='dependency_data',
            name='and_data',
        ),
        migrations.RemoveField(
            model_name='dependency_data',
            name='or_data',
        ),
    ]
