# Generated by Django 6.0.7 on 2026-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0017_remove_dependency_or_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='or_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependency_data',
            name='and_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependency_data',
            name='or_data',
            field=models.BooleanField(default=False),
        ),
    ]
