# Generated by Django 6.0.7 on 2026-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0018_dependency_or_only_dependency_data_and_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreporatoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.CharField(max_length=50)),
                ('topbottom', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('selected_processes', models.JSONField(blank=True, default=list)),
                ('elastic_status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('jobno', 'topbottom', 'process')},
            },
        ),
    ]
