# Generated by Django 6.0.7 on 2026-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0021_normalize_preporatory_selected_processes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRibdelPreparatory',
            fields=[
                ('rowno', models.BigIntegerField(db_column='RowNo', primary_key=True, serialize=False)),
                ('jobno', models.CharField(max_length=50)),
                ('topbottom_des', models.CharField(blank=True, db_column='TopBottom_des', max_length=50, null=True)),
                ('siz', models.CharField(max_length=35)),
                ('clrcomb', models.CharField(max_length=50)),
                ('unitname', models.CharField(blank=True, db_column='UnitName', max_length=50, null=True)),
                ('lotno', models.CharField(blank=True, db_column='LOTNO', max_length=10, null=True)),
                ('delpc', models.IntegerField(blank=True, null=True)),
                ('indpart', models.CharField(max_length=50)),
                ('process', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'view_ribdel_preparatory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RibdelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('jobno', models.CharField(max_length=50)),
                ('topbottom_des', models.CharField(blank=True, max_length=50, null=True)),
                ('clrcomb', models.CharField(max_length=50)),
                ('siz', models.CharField(max_length=35)),
                ('lotno', models.CharField(blank=True, max_length=10, null=True)),
                ('total_qty', models.IntegerField()),
                ('entered_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
