# Generated by Django 6.0.7 on 2026-10-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0023_ribdelentry_rowno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ribdelentry',
            name='rowno',
        ),
    ]
