# Generated by Django 6.0.7 on 2026-10-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0024_remove_ribdelentry_rowno'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_data',
            name='entry_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
