# Generated by Django 6.0.7 on 2026-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0025_assembly_data_entry_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='verify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dependency',
            name='verify_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
