# Generated by Django 6.0.7 on 2026-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0026_dependency_verification_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_unit_permission',
            name='app',
            field=models.CharField(choices=[('qcapp', 'QC App'), ('live_app', 'Live App'), ('machine_transfer', 'Machine Transfer')], max_length=20),
        ),
    ]
