# Generated by Django 6.0.7 on 2026-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0027_machine_transfer_app_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_unit_permission',
            name='app',
            field=models.CharField(choices=[('qcapp', 'QC App'), ('live_app', 'Live App'), ('machine_transfer', 'Machine Transfer'), ('employee_allocation', 'Employee Allocation'), ('bundle_scan', 'Bundle Scan')], max_length=20),
        ),
    ]
