# Generated by Django 6.0.7 on 2026-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0028_alter_user_unit_permission_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_data',
            name='unit_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
