# Generated by Django 6.0.7 on 2026-10-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_live_scan', '0029_assembly_data_unit_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='bundle_transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('line', models.IntegerField()),
                ('job_no', models.CharField(max_length=50)),
                ('tb_id', models.IntegerField()),
                ('tb_name', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('seq', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('bundle_id', models.CharField(max_length=50)),
                ('bdl_no', models.CharField(max_length=50)),
                ('mbud', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('size_id', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('pc', models.CharField(max_length=50)),
                ('entry_mode', models.DateTimeField()),
                ('lot', models.CharField(max_length=50)),
                ('emp_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
