# Generated by Django 6.0.7 on 2026-10-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herofashion', '0005_loginlog'),
        ('hr_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='hr_module.dashboardcard')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_card_permissions', to='herofashion.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'card'), name='hr_unique_role_card')],
            },
        ),
    ]
