# Generated by Django 6.0.7 on 2026-10-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0002_dashboardcard_rolecardpermission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolecardpermission',
            name='hr_unique_role_card',
        ),
        migrations.RemoveField(
            model_name='rolecardpermission',
            name='card',
        ),
        migrations.RemoveField(
            model_name='rolecardpermission',
            name='role',
        ),
        migrations.DeleteModel(
            name='DashboardCard',
        ),
        migrations.DeleteModel(
            name='RoleCardPermission',
        ),
    ]
