# Generated by Django 5.2.12 on 2026-07-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasWorklist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_collation='Latin1_General_CI_AI', db_column='Description', max_length=255)),
                ('type', models.CharField(db_collation='Latin1_General_CI_AI', db_column='Type', max_length=100)),
                ('active_inactive', models.BooleanField(db_column='Active_Inactive')),
            ],
            options={
                'db_table': 'Mas_Worklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsWorkentry',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='Latin1_General_CI_AI', db_column='UserName', max_length=100)),
                ('entrydate', models.DateField(db_column='EntryDate')),
                ('project', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Project', max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Category', max_length=100, null=True)),
                ('subcat', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='SubCat', max_length=100, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, db_column='StartDateTime', null=True)),
                ('startstatus', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='StartStatus', max_length=20, null=True)),
                ('description', models.TextField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Description', null=True)),
                ('enddatetime', models.DateTimeField(blank=True, db_column='EndDateTime', null=True)),
                ('endstatus', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='EndStatus', max_length=20, null=True)),
                ('duration', models.CharField(blank=True, db_collation='Latin1_General_CI_AI', db_column='Duration', max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('durationminutes', models.IntegerField(blank=True, db_column='DurationMinutes', null=True)),
            ],
            options={
                'db_table': 'Trs_Workentry',
                'managed': False,
            },
        ),
    ]
