# Generated by Django 5.2.12 on 2026-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_reports', '0002_masworklist_trsworkentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasWorklist',
        ),
        migrations.DeleteModel(
            name='TrsWorkentry',
        ),
    ]
