# Generated by Django 5.2.12 on 2026-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_reports', '0003_delete_masworklist_delete_trsworkentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StAtt',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('code', models.IntegerField()),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('cat', models.CharField(blank=True, max_length=70, null=True)),
                ('intime', models.TimeField(blank=True, null=True)),
                ('outtime', models.TimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, db_column='Duration', max_length=10, null=True)),
            ],
            options={
                'db_table': 'st_att',
                'managed': False,
            },
        ),
    ]
